### ISSUE TITLE
GPS edit > IPTC:Sub-location exceeds length limit

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#100]
field location truncated or not? (length limit or commas?)
https://exiftool.org/forum/index.php?topic=2710.0

![ScreenShot 2020-12-08 a las 11 45 59](https://user-images.githubusercontent.com/693328/101498903-64b75900-394b-11eb-9af5-8b890a04a004.png)

original file: 
![MA-DP122766](https://user-images.githubusercontent.com/693328/101499290-dc858380-394b-11eb-8275-deae8ca20ae7.jpg)

Best,
Martin

MacOS 10.15.7
jExifToolGUI 1.8.1
openjdk version "11.0.8"

**Comment by hvdwolf** [comment]
It is indeed the limitation in the IPTC tags  (`Sub-location | string[0,32]`).
If I more or less repeat your example by simply searching `Buenos Aires`, I get "Ciudad Autónoma de Buenos Aires, Argentina".
If I remove the commas, I simply get a 1-character longer string.
If I remove all commas and spaces, I get a 7 character longer string. (CiudadAutónomadeBuenosAiresArge).

If I do ` exiftool -m -iptc:sub-location="Ciudad Autónoma de Buenos Aires, Argentina" example.jpg`. I don't get an error.
When I no do `exiftool -S -G0 -iptc:all example.jpg` I get,
"[IPTC] Sub-location: Ciudad Autónoma de Buenos Aires, Argentina".

I have already been thinking earlier about adding the `-m` as preference option, but it also means that you might do something wrong and not even know it as the "minor error" is not displayed. In case of the IPTC:sub-location tag it might be desired functionality. In other (archiving?) options, you really might want to know when someting is not working correctly: either the program or the tag or the value.
If I make it a preference setting it really needs some warning with it.

On the other hand: I could also add a checkbox in below tab "Also save IPTC location information" and only here a second checkbox "ignore minor errors using -m"
![xmp-iptc location](https://user-images.githubusercontent.com/4520361/101513595-a7ddf000-397c-11eb-863d-47c498600b2b.png)

So there are some pros and cons to consider when using this `-m` option.

**Comment by hvdwolf** [comment]
If you want to that in the current version, you could copy the value from the location and/or city and execute it for the selected image on the "Exiftool Commands" tab like:
`-m -iptc:sub-location="Ciudad Autónoma de Buenos Aires, Argentina and much more characters" -iptc:city="Ciudad Autónoma de Buenos Aires, Argentina and much more characters"`

**Comment by mrtngrsbch** [comment]
mmm...
How do you think about these options?

a. put the option [-m] in a checkbox ?
b. show the character limit of each field? Ex. field limit 32 chars

Note:
The data contained in this image was obtained from OSM, from the "copy to gps tab" button
"Location: Ciudad Autónoma de Buenos Aires, Argentina" is redundant but Argentina is a Country

best

**Comment by hvdwolf** [comment]
I know it came from the copy option. I did the same.
Most of the time I do not blindly copy it, but strip the unnecessary data.
For example. When searching on "Eiffel Tower", I get:
`Tour Eiffel, 5, Avenue Anatole France, Quartier du Gros-Caillou, Paris 7e Arrondissement, Paris, Île-de-France, France métropolitaine, 75007, France`.
I really don't need/want the `Paris, Île-de-France, France métropolitaine, 75007, France` part as city and country are already covered. It is simply how Nominatim delivers it, and I don't know where to cut it off (appart from the last comma followed by the country).

And when searching for "Christ the redeemer, rio de janeiro" , I get `Cristo Redentor, Estrada do Corcovado, Santa Teresa, Zona Central do Rio de Janeiro, Rio de Janeiro, Região Geográfica Imediata do Rio de Janeiro, Região Metropolitana do Rio de Janeiro, Região Geográfica Intermediária do Rio de Janeiro, Rio de Janeiro, Região Sudeste, 22470-180, Brasil`
Now that's long! (and it is in Spanish)

With regard to your a) and b).
That might be an option as it only relates to the IPTC fields (city (32), Sub-location (32) and Country-PrimaryLocationName (64)). The XMP fields are "strings" and much longer. Sometimes even "String+" meaning that it can be a set (array) of strings.

Normally the length restriction will only apply to the iptc:Sub-location tag as city is hardly ever longer than 32 characters and there is no country in the world exceeding 64 characters.
(And I see that I don't save the iptc:Province-State: bug!)

**Comment by hvdwolf** [comment]
It is now working using the optional "-m" parameter.
![xmp-iptc-m](https://user-images.githubusercontent.com/4520361/101628293-e5478980-3a1f-11eb-983d-ed3e9f1d9640.png)

Using the "christ the redeemer, rio de janeiro" from the nominatim searchI now get the full string.
It is so long that I now made a screenshot of the "Exiftool Commands" tab
 
![EC-iptc](https://user-images.githubusercontent.com/4520361/101628469-25a70780-3a20-11eb-8135-e3d90fa625d9.png)

In the next release (don't know when yet).

**Comment by mrtngrsbch** [comment]
It's true, Nominatim delivers a long chain that is often not necessary.
I figured a user in a hurry wouldn't stop to edit that string.

The advanced solution you have given is excellent, I think nothing more is needed

merci
