### ISSUE TITLE
Windows - Admin privileges

### ISSUE THREAD

**Issue by Kvcd12** [hvdwolf/jExifToolGUI#101]
I installed jExifToolGUI-1.8.1-win-x86_64_with-jre.zip into a standard (not Admin) account.

I am using Oliver Betz's alternate ExifTool Windows installer.

When I open jExifToolGUI, I see the jExifToolGUI splash screen, but the application does not open.

The log shows jExifToolGUI identifies the correct location of ExifTool.

If I open jExifToolGUI with Admin privileges, I see the jExifToolGUI splash screen, and the application opens.

Is there a way to open jExifToolGUI without Admin privileges?

Thank you.

**Comment by Kvcd12** [comment]
I think I have identified why Admin privileges are required on this computer:  a DLL file (sqlite ....) is placed, temporarily, in the AppData folders during the opening process.

**Comment by hvdwolf** [comment]
I really have no idea. You are the first to encounter this.

**Comment by Kvcd12** [comment]
On this computer, the AppData folders are "locked down".  No EXE, no DLL, ....

**Comment by hvdwolf** [comment]
"This computer".
Did you do that yourself or is this some business pc/laptop from your work with group policies rolled out to prevent users from altering their pc toomuch, or to prevent installation of "admin based" installers (most are).

**Comment by Kvcd12** [comment]
Did it myself.  Thus, I could undo it.  But it has been valuable.

**Comment by Kvcd12** [comment]
I will close this out.  Thank you.
