### ISSUE TITLE
App fails to launch on macOS Big Sur

### ISSUE THREAD

**Issue by arashnrim** [hvdwolf/jExifToolGUI#102]
Hello!

Firstly, thanks for working on creating this product to make editing EXIF data much easier. I personally find it really difficult to use `exiftool` with all its commands and arguments required. From what I've seen of the app's screenshots, this tool looks like just the thing I need for editing the metadata of my photos.

Unfortunately, though, it seems like I've come across a problem. I'm attempting to run jExifToolGUI on macOS Big Sur (it must be quite a hassle already to deal with Big Sur issues!). The main problem lies in the fact that nothing happens once the `.app` is executed; after digging a little, I presume that this issue was caused due to a missing file — or, at least, that's the issue that Big Sur gave me.

The version I've installed is the `with_jre` variant.

Here's a basic rundown of what I've done thus far:
1. Moved the app to `username/Applications/` and bypassed Apple's security warning (by control-clicking Open) — app failed to launch
2. Opened Security & Privacy in System Preferences to allow Full Disk Access to jExifToolGUI — app failed to launch
3. **Tried running executable (located in `jExifToolGUI.app/Contents/MacOS/jexiftool.gui`) — app failed to launch, but noticed something**
4. Moved the app to `/Applications` — app failed to launch

When running the direct executable in the app's Contents folder (see step 3 of the rundown), here's what was outputted from the Terminal:
```
/Users/username/Applications/jExifToolGUI.app/Contents/MacOS/jexiftoolgui ; exit;
username@My-Mac ~ % /Users/username/Applications/jExifToolGUI.app/Contents/MacOS/jexiftoolgui ; exit;
Saving session...Error: Unable to access jarfile /Users/username/Applications/jExifToolGUI.app/Contents/MacOS/jExifToolGUI.jar

...saving history...truncating history files...
...completed.

[Process completed]
```

Sure enough, there wasn't a `.jar` file located in the same directory as the executable; I presume that this was the source of error. Here's a screenshot of what the MacOS folder looked like:
<img width="777" alt="Screenshot 2020-12-24 at 9 41 28 PM" src="https://user-images.githubusercontent.com/47273556/103092011-d64f0280-45ed-11eb-9250-e5a22297fc1e.png">

Is this a valid issue that is meant to be fixed? I hope my elaborations helped in explaining my issue here. Thanks in advance for the help!

**Comment by hvdwolf** [comment]
I really don't understand this. I just checked the package and the jExifToolGUI.jar is definitely inside the MacOS folder together with `jexiftoolgui`, `logback.xml` and the folder `jre`.
When talking about safty/security, I can't imagine why Big Sur would remove the jar and leave the `jexiftoolgui` and the executables in it.

Did you also check the downloaded version about its contents?

**Comment by arashnrim** [comment]
Thanks for the reply!

I just grabbed another copy from the Releases page to see if this had been an issue that was caused by Big Sur. Checking the contents of the newly-downloaded version (directly on the `.dmg` image), the `.jre` file wasn't included together in the same directory. Just to verify everything I've done the same steps as I've done above, but directly on the opened `.dmg` image. Still the same thing, with the Terminal outputting the same thing.

**Comment by arashnrim** [comment]
Here's another update from what I've seen.

It appears that the `with_jre` variant does not have the `.jre` file in the `jExifToolGUI.app/Contents/MacOS/` directory, but the variant without JRE has. I've copied over the `.jre` file from the variant without JRE to the variant with, and it works. I presume directly downloading the `.jre` file from Releases and moving it to the directory above will work too, but I haven't tried that to say it works.
