### ISSUE TITLE
Add option to not add “jExifToolGUI 1.8.1“ metadata to each edited image

### ISSUE THREAD

**Issue by sendc** [hvdwolf/jExifToolGUI#103]
Problem: When editing a jpg’s metadata, two additional metadata tags are added without me being able to change that.

Code: In **Utils.java** at the end of function **AlwaysAdd()**. 
I don’t see why this is necessary. It already bad enough that exiftool itself adds another tag.

**Comment by hvdwolf** [comment]
Sorry, but they will stay in.

Did you ever work with Adobe photoshop, Digikam, iPhoto, etcetera?
Most programs add their own metadata tags. And we are now talking about images.
Did you ever see what movie editors add? or the Microsoft suite? (no image meta data in this case)

I don't understand either why it is so annoying. My photos contain 200 - 350 metadata tags, plus my two tags and the exiftool tag.
