### ISSUE TITLE
Preview images cache

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#104]
I usually open folders with hundreds of images and this operation takes a long time.
Indeed, the task of generating the images takes a lot of resources.

1. Could an option be added to control the size of the preview image?
2. Could this generated folder be saved in the cache?
3. Another solution?

best

**Comment by hvdwolf** [comment]
First the questions, then an explanation:
1. Yes, But do you mean the (to be) cached image or the preview in the program? or both?
2. Yes. It can.


When looking at JPGs (later than approx. 2012) or RAW images, they mostly have a thumbnail image (160x120) and a preview image (3 options for the name) **INSIDE** the main image file. These preview images vary from 640x480 to 1920x1080. The fastest option is to extract the thumbnail (first, no resizing necessary) and then when not available to extract and resize the Preview.
In case both are not available I resize the complete image to 160x120 (this is a "default" in the image world). This resizing from full image to thumbnail takes the longest.
I currently save thumbnails, (resized) Previews or the resized image in the OS tmp folder under a subfolder `jexiftoolgui`. This could be an "image cache" folder of course.
Tiff (or PNG) images never have thumbnails or preview images (apart from the TIFF based RAW image formats). So I have to resize every TIFF. You are a "TIFF user" and have therefore the slowest loading times.

So yes: I can create a cache folder containing these images which should speed up loading in subsequent loading. Especially for TIFFs.

What I then would suggest for configuration/options:

1. Configurable cache folder. By default under `<user home>/jexiftoolgui_data/cached_images` (`<user home>/jexiftoolgui_data` is the current data folder). This could/should then be combined with request #79.
2. Configurable size of preview in program
3. "Delete cached images after ... days" option

**Comment by mrtngrsbch** [comment]
1. At this moment I only refer to the image saved in the cache
2. Nice

In my experience... many images do not contain an internal preview image. This depends on the application with which it was created or if it has passed an optimization process [For example, for my web images I use ImageOptim, which eliminates any secondary data].
Indeed, the most reasonable thing to do is to look for the preview images and, if they do not exist, to create them.

My issue is focused on the problem of re-reading folders with many (many) files every time you open JTG, which is very painful to work with.

The solutions you offer are excellent and I think it would solve this problem. Other applications use the same mechanism successfully.

Also... being able to set up the preview images (640x480 to 1920x1080 ?) would certainly be a nice option.

best

**Comment by hvdwolf** [comment]
1. Why the images in the cache? That means that it will not be much faster as I have to resize them again for the thumbnail in the program. So why the ones on disk? I thought you wanted to vary the size of the thumbnails in the program.

When I said that jpegs do contain a preview image I was talking about jpegs from cameras. I know that some scanners do this as well where others don't do it (mine doesn't).

The preview image being 640x480 or up to 1920x1280 is when you double-click the thumbnail?
I do it now fullscreen as my app is focused on camera images being 5~24 Megapixels. In that case if you want to see it correctly, you do need full-screen (I actually thought of building a zoom function to be able to better view this megapizel images). Next to that: I also built in the back/forward buttons so you can circle to all images. Again: With big photographic images that looks much better.

Are your tiffs in general smaller than "screen size"?

**Comment by mrtngrsbch** [comment]
humm... 
I probably expressed myself badly or we mixed two similar ideas.
1. Change the size of the thumbnails
2. Get JTG to open a recurring folder faster

At the moment I don't mind the size of the thumbnail.
But delaying the reading of a recurring folder can be distressing.

- Yes, a 640x480 preview would be excellent !
- My tiffs are usually in original camera or scanner size +3000 px
mmm...This makes me think of something I hadn't noticed... JTG is not an image browser!
Maybe this is a barrier in the definitive adoption of JTG (?)

**Comment by hvdwolf** [comment]
So what you want is to resize and cache the images to something like 640x480 (640x400) and show the images either full-screen or to that preset cached format. (And in case of deviating sizes: horizontal size <= 640; vertical size <= 480). 
Like mentioned: I want to see my 12 and 13.5 Megapixel images always (!) full-size, and possibly also with zoom option.
So it should be a choosable option: full-size or to some preset, cached format.

JTG is indeed not an image browser, although you can simply loop though all images in fullscreen viewer.
JTG is a metadata browser/editor.
That is also the difference with having cached images when wanting to do metadata editing.
You want to view cached images, but of course want to see and edit the metadata from the original image. That makes it a lot more complex. That also requires loading the preview and reading the metadata from the original image. That is a double action.
(Or: I need to make a cached image and copy all metadata to the cached image. Of course I can't copy file metadata to the smaller image. This 2nd option is also an option, but I don't think the right option.)

A "normal" image browser doesn't have to do that which makes it always faster, no matter whether you cache images or not.

**Comment by mrtngrsbch** [comment]
think I'm understanding some low-level complexities of the mechanism...
But yes, you're right and so am I with your first paragraph.

I leave this issue, its priority and the real needs of the users to your discretion; you have more experience with them.

**Comment by hvdwolf** [comment]
Do you have some 10-15 full size tiffs for me which I can download somewhere?
Also to do tests in loading strategies.
I also really think I need to drop java 8. java 11 is faster and has better resize options. I know you use java 11, but my code is for java 8. Maybe that java 11 code makes it faster anyway.

**Comment by mrtngrsbch** [comment]
Of course, here I have uploaded about 15 images in RAF, TF and JPG
https://app.box.com/s/he6jiub6adsmi6qa13qyegbwgx6yimjc


Discussing strategies... (just a comment)

When I have to edit the metadata of many large images, I have several strategies, depending on the infrastructure and software.

Scenario: "Project X to record metadata in 3300 in TIFF @48MB each" (158.4 GB !)

1. Create a thumbnail copy of each image [mogrify -resize 256x256 -path thumb *.tif]
2. Edit the metadata in Sheets...
3. Save the metadata in the images with a bash ex script.[exiftool -title -description -etc- image.tif]
4. Testing
5. Verification + Customer OK
6.Export metadata to CSV [exiftool -csv -title -description -etc- *.tif > export.csv]
7. Save the metadata in original images
8. END

Working with small images has two purposes:
a. to record metadata (or to modify a file) makes, if one works in cloud (Box, One, etc.) the time of rewriting and internet bandwidth makes the task very long and painful.
b. modifying small images is much faster, since it is common to find some error in this task.

Obviously, I always use OpenRefine because the data never comes OK. You must check many things: Spanish accents, dates, places...

As you know... my issues are focused on that problem, but I believe that any photographer can benefit from them.

best

**Comment by hvdwolf** [comment]
I fully understand your requirements, but it's a very specific use.

1. Caching images is a very useful request.
2. I prefer to limit the use of external tools as much as possible (imagemagick mogrify), as it will always give dependency issues on the several platforms. An option is to build in the option/functionality and if mogrify is not available a user can't use it. same for dcraw for example for which I have request, and same as I treat heic/heif which currently can only be used on MacOS, or Gimp xcf converters which are only available on Linux/MacOS.
3. Exporting metadata from images to CSV. That should not be an issue. Currently there is the "general purpose" CSV export, but modifications on this one can be built as well.
4. The most difficult part: Time!
5. The second difficult part: Time!

**Comment by mrtngrsbch** [comment]
It is indeed a specific requirement.
I think if I had to define it in one line, I would say that it is part of a "Metadata Audit".

- Obviously, it is NOT my intention that JTG does everything. But if I could get him to do everything ExifTool does (read and write metadata) it would be great.
1. Indeed it is. Unfortunately I do not know the opinion of other users.
2. Imagemagick mogrify: Personally I'm very satisfied with using mogrify on the outside and I don't think it's wise to incorporate that feature into JGT, because every user can do it with the tool they want.Better not to get into that mess and I don't like dependencies much either. 
_Note: I'm thinking for the future a feature to import a bulk CSV to rewrite the metadata of the open images (this would allow to create a workflow to export to OpenRefine, make corrections and then re-import). I see that the 'import' button is active now. I'm going to create an issue to get it out while JGT is not exporting._
3. Currently the export of metadata is excellent! Thank you very much Harry for this wonderful tool. 
4. This year I will have Java resources to collaborate with the code ;-)
5. This year I will have Java resources to collaborate with the code ;-)

**Comment by mrtngrsbch** [comment]
It is indeed a specific requirement.
I think if I had to define it in one line, I would say that it is part of a "Metadata Audit".

- Obviously, it is NOT my intention that JTG does everything. But if I could get him to do everything ExifTool does (read and write metadata) it would be great.
1. Indeed it is. Unfortunately I do not know the opinion of other users.
2. Imagemagick mogrify: Personally I'm very satisfied with using mogrify on the outside and I don't think it's wise to incorporate that feature into JGT, because every user can do it with the tool they want.Better not to get into that mess and I don't like dependencies much either. 
_Note: I'm thinking for the future a feature to import a bulk CSV to rewrite the metadata of the open images (this would allow to create a workflow to export to OpenRefine, make corrections and then re-import). I see that the 'import' button is active now. I'm going to create an issue to get it out while JGT is not exporting._
3. Currently the export of metadata is excellent! Thank you very much Harry for this wonderful tool. 
4. This year I will have Java resources to collaborate with the code ;-)
5. This year I will have Java resources to collaborate with the code ;-)

**Comment by hvdwolf** [comment]
1. It is on my ToDo list.
2. With regard to mogrify or any other external program. 
  I call exiftool also as an external program. Currently we have favorites for the ExifTool Commands and for the database commands. I think it would be rather simple to extend this favorites to "external commands" for any external (command line) program with something like `mogrify -resize 256x256 -path thumb %image%`, and execute that on the selected images. Where %image% (or $1 or whatever variabele) is the image when JTG loops through the selected images). 

`4. and 5. : Nice. I'm only an amateur. A good programmer might in the same go do some necessary improvements to the program code, that I do not even see.

**Comment by hvdwolf** [comment]
You gave me 15 of those big tiff images. It turns out that photoshop also adds thumbnails to its images. Of course photoshop does not comply to international standards and does not call the thumbnail `<name>_ThumbnailImage.jpg`, but `<name>_PhotoshopThumbnail.jpg`.
So JTG now supports photoshop thumbnails as well (because exiftool "simply" extracts a thumbnail whatever the name).
Anyway: Please try [this version](https://mega.nz/file/YU1h3agS#mSXrOHxhnalA3ik7WhNm3zzps8E_S53xzXhbLvnOEyQ) with those big tiffs (and compare it with the current JTG).
Loading now seems to be a 100x faster (I did not measure).

Modifying metadata does hardly make a difference whether it is a big file or not

**Comment by mrtngrsbch** [comment]
> 2. With regard to mogrify or any other external program.
>    I call exiftool also as an external program. Currently we have favorites for the ExifTool Commands and for the database commands. I think it would be rather simple to extend this favorites to "external commands" for any external (command line) program with something like `mogrify -resize 256x256 -path thumb %image%`, and execute that on the selected images. Where %image% (or $1 or whatever variabele) is the image when JTG loops through the selected images).
> 
> `4. and 5. : Nice. I'm only an amateur. A good programmer might in the same go do some necessary improvements to the program code, that I do not even see.

2. Very interesting your approach, I like it ;-)With the same idea we could do many operations for image processing.
For image optimisation I use ImageOptim [https://github.com/ImageOptim/ImageOptim] which is excellent, but for MacOS. ImageOptim is also a GUI for other applications, such as; PNGCrush, AdvPNG, JpegOptim, MozJPEG...
Personally I think it would be great if JTG could do all that, but it is certainly an effort that has to be planned and thought about if we want to incorporate it into the JTG project, but yes, it would be great if it could be done. [And I am conscious that the objective of JTG is an ExifTool GUI].

4,5. This project has just started and I have not yet written the issues. The focus will be on reading and writing metadata standards for archives (ISADG, EAD, SPECTRUM...) for audit as well as improving the GUI for these operations. For example: see the ISADG (or other) metadata in the column 'File Data'. We will also have the energy to improve the tool where necessary. This also depends on the sponsors ;-)

![image](https://user-images.githubusercontent.com/693328/104818557-111c1300-5807-11eb-8832-412ecbd3870b.png)

**Comment by mrtngrsbch** [comment]
> You gave me 15 of those big tiff images. It turns out that photoshop also adds thumbnails to its images. Of course photoshop does not comply to international standards and does not call the thumbnail `<name>_ThumbnailImage.jpg`, but `<name>_PhotoshopThumbnail.jpg`.
> So JTG now supports photoshop thumbnails as well (because exiftool "simply" extracts a thumbnail whatever the name) which speeds up loaing enormously.
> Anyway: Please try [this version](https://mega.nz/file/YU1h3agS#mSXrOHxhnalA3ik7WhNm3zzps8E_S53xzXhbLvnOEyQ) with those big tiffs (and compare it with the current JTG).
> Loading now seems to be a 20-50x faster (I did not measure).
> 
> Modifying metadata does hardly make a difference whether it is a big file or not, as it does not have to access the huge image data chunk, but only the metadata header.

Coooooool...
I took the test with 60 images [2.88GB].

new jar: 29"
v1.8.2: 1'25"

best
