### ISSUE TITLE
jexif tool does not launch

### ISSUE THREAD

**Issue by Sigi11** [hvdwolf/jExifToolGUI#108]
Hello,
Just installed and dowloade on Catalina:
- jexif Tool
- Exif Tool
- Java

When I try to open jexif tool nothing happens. I am sure I am missing something. Thank you for your help.

Sigi

**Comment by hvdwolf** [comment]
Do you mean jexif Tool or jExifToolGUI?
And what did you download? the jar, the app, the full app?
And depending on what you downloaded: how did you open it?
Please check the logs folder inside your home folder. Hopefully you will find logs there telling something.

**Comment by Sigi11** [comment]
I downloaded
JExifToolGui: jExifToolGUI-x86_64-macos-1.8.1-with_jre.dmg.zip

I have the JExiToolGUI app in the applications folder. 
I downloaded Exif Tool from the Phil Harvey site
and I have Java V8 build 281 installed.

When I open JExifTool Gui nothing happens, no screen pop or anything else.

I would not know where to look at the looks folder in my user library

**Comment by hvdwolf** [comment]
the logs folder. Not in your user library, but in your user home folder.
Please also check the last post of issue #102 
That user mentions that the with jre version does not contain the jre. That is not possible as you can even clearly see from the size of the downloadable files. 
But please check if that also happens to you. I have no idea whether MacOS in some cases removes the JRE.

**Comment by Sigi11** [comment]
I think I give up and look for something else to manage my Exif data. I am just a photographer and not a computer expert. I just do not know where to look what you are asking me to do.
Thanks

**Comment by Sigi11** [comment]
I have look now in User/Library/Logs and there is no entry in regards to Jexiftoolgui

**Comment by hvdwolf** [comment]
No, the logs are in `/User/<username>/logs` . They are named per date_time (YYYYMMDD-HHMM) when JTG was started.

I assume you installed the jExifToolGUI.app in Applications.
If so, can you please do  from a terminal `/Applications/jExifToolGUI.app/Contents/MacOS/jexiftoolgui`. That does start the application directly from the command instead of "the normal way". It will also echo to the screen what might probably go wrong.

And lastly (if you still want to do that): Please download the jar and from a terminal in the folder where you downloaded the jar, do a `java -jar jExifToolGUI.jar`. If java is correctly installed, that should work

**Comment by Sigi11** [comment]
I do no have a log folder in that path.

Terminal says: Unable to access jarfile /Applications/jExifToolGUI.app/Contents/MacOS/jExifToolGUI.jar 
in regards to Java I get from Terminal: No Java runtime present, requesting install.

**Comment by Sigi11** [comment]
When you say "download the jar" - What should I download exactly?

**Comment by Sigi11** [comment]
Hello hvdwolf,
no worries anymore. I have deleted everything and start looking for something else. Thank you nevertheless for your help.

**Comment by hvdwolf** [comment]
> I do no have a log folder in that path.
> 
> Terminal says: Unable to access jarfile /Applications/jExifToolGUI.app/Contents/MacOS/jExifToolGUI.jar

That's not what I wrote.
I wrote: `/Applications/jExifToolGUI.app/Contents/MacOS/jexiftoolgui`  and to start that from a terminal.

You wrote in your first post that you installed java, however you now write:
>
> in regards to Java I get from Terminal: No Java runtime present, requesting install.

So you only downloaded java. You did not install it.


Anyway, good luck in finding another tool.

**Comment by houseofc** [comment]
Download the app and copy to Applications
Download jExifToolGui.jar
ctl-click on the app jExifToolGUI.app and select Show Package Contents
copy jExifToolGui.jar into the package directory Contents/MacOS

Then you should be able to open the app and run it. I could not get it to actually update the data in my images (it claimed to have saved the edits but did not), but it is fine as a viewer. It will give you a good start to figuring out what you want to change using the command line tool, at any rate.

**Comment by Sigi11** [comment]
Hello houseofc,

tried it again:
- downloaded app for mac. Perl version and installed with terminal as instructed on the website from Phil Harvey
- downloaded land installed latest version of Java. can see it in System Preferences
- downloaded jExifToolGui.jar and copied the downloaed file to the location you mentioned above

As before, when double click on the app JexifToolGui it looks like it opens but then nothing happens. No error message or anything else.

**Comment by houseofc** [comment]
Did you download the larger one with-jre? That's the one I used, did not try the other. 
Then open a terminal and paste this:
/Applications/jExifToolGUI.app/Contents/MacOS/jexiftoolgui

If it is missing anything else, you should at least see what.

When it doesn't even open, it will not have started enough to get to where it can write a log.

**Comment by Sigi11** [comment]
Ok. The terminal command did the trick and it opened.
After opening the app with terminal I can also open it normally via the Dock.

Can you tell me what was wrong before - in laymens terms if possible:))))

**Comment by houseofc** [comment]
An OSX app is a special folder that, in the Finder, looks like a file. Everything the app needs to run is in the folder. When you "Show Package Contents", you can look at or modify the app's contents.

When you ran the app from the command line (in Terminal) (you can also use the open command, "open /Applications/jExifToolGUI.app", if you do not want to explore the package to find out the actual name and location of the launchable file) the error message tells you there is something missing:
Unable to access jarfile /Applications/jExifToolGUI.app/Contents/MacOS/jExifToolGUI.jar

So I looked at the downloads list and saw that the missing piece (the jar file jExifToolGUI.jar) was available for download, I downloaded it and put it in the part of the package where the error message said it was missing from (/Applications/jExifToolGUI.app/Contents/MacOS/).

O/T:
Let me put in a plug for getting comfortable with the Terminal. It can get you out of a lot of trouble (ok, and into some too) I know I sound like a grumpy old lady, "kids these days don't know how to use the command line!" but I grew up in mainframes 40 years ago, so get off my lawn :-) 

Here's a command to get you started: 
ifconfig
It will tell you more than you want to know about your network connections, and can be really useful when your network gets fubar'd.
