### ISSUE TITLE
Using a proper logger instead of System.out.println

### ISSUE THREAD

**Issue by Swissbite** [hvdwolf/jExifToolGUI#11]
A proper logger can enable/disable logging levels. You are able to define the levels on certain stages. Later on, you would also be able to change the level on application startup time (or even on setting settings) so that issues can be logged, stored and transmitted.

Benefit: You'll always know where the log entry was generated on which timestamp. You'll never have to find out which log message comes from which line of code.

Benefit: It's easy to use, all you have to decide is on which level a log message should be thrown.

**Comment by hvdwolf** [comment]
I trust your expertise. I'm not that far but I will see it when it is there.

**Comment by Swissbite** [comment]
#17 solves this issue.

**Comment by hvdwolf** [comment]
I merged the pull request but get errors on building on
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

```
Error:(43, 26) java: cannot find symbol
  symbol:   class Logger
  location: class org.hvdw.jexiftoolgui.mainScreen
Error:(43, 42) java: cannot find symbol
  symbol:   variable LoggerFactory
  location: class org.hvdw.jexiftoolgui.mainScreen
```
Does it retrieve from the web when compiling or does it need to be added to the repo?

**Comment by Swissbite** [comment]
I just checked the compile on my side and it works ;-)

Did you a gradle build or "just" an IntelliJ Build? If you did an IntelliJ Build, did you refresh the IntelliJ cache for gradle? Have a look at the [screenshot](https://ibb.co/6Jky7p5).

**Comment by hvdwolf** [comment]
I did a build from IntelliJ, then a rebuild project from IntelliJ. Then I did a direct command-line "./gradlew clean" and "./gradlew build". Then I did your gradle intellij cache refresh (I thought that all was re-initiated when you did the "rebuild project").
And finally (remotely during early lunch) I simply removed the .gradle and build folder.
That was issue 1.
And then I got the error that my JVM (8) and source setting (11) were different. Obviously my gradle JVM was still an java 8 JVM. Java 11 is the only used default, but somehow gradle managed to find java8. I now removed that from my system and set 11 as JDK in my gradle settings AND in my project structure settings (which was also still at 8).
I assume either intelliJ or gradle or your configuration (perhaps?) mixed this java8 versus java 11 as I started from 8, or all these components together need some manual tweaking.

So now it builds. When I use the build/distributions, using all the combined jars it works. If I try to use the fatJar from build/libs, I get:
```
FoundError: org/slf4j/LoggerFactory
	at org.hvdw.jexiftoolgui.Application.<clinit>(Application.java:17)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

```
So the necessary dependency jars are not yet packaged in the fatJar.
I will also try to look at that tonight myself.

**Comment by Swissbite** [comment]
This is true. The default jar file does not create a fat jar (i just realised).
If you like to solve it by yourself, then this is the hint link: https://www.baeldung.com/gradle-fat-jar

Another hint: We are using kotlin dsl for gradle, so you may also read about it ;-)

**Comment by hvdwolf** [comment]
Hi,

I already found it on the web and pushed a commit.

Harry


Op wo 5 jun. 2019 om 13:50 schreef David Daester <notifications@github.com>:
