### ISSUE TITLE
Edit Data - allow comma (not separator) in String+ values 

### ISSUE THREAD

**Issue by MetadataDeluxe** [hvdwolf/jExifToolGUI#114]
I would like to be able to use a String+ value that contains a comma. This use case is very common in many controlled vocabularies such as the Library of Congress or the Getty Vocabularies. For example:
Subject = United States History Civil War, 1861-1865
Person in Image = Hatshepsut, Queen of Egypt

When this type of value is saved in jExifToolGUI, the value is split into separate list items:

Subject
- United States History Civil War
- 1861-1865

Person in Image
- Hatshepsut
- Queen of Egypt

Would it be possible to specify a different separator, such as (";") or (" | ")? Or would it be possible to surround the value with quotes, e.g., "United States History Civil War, 1861-1865" and "Hatshepsut, Queen of Egypt"? I tried this, but got the following result:

Error: File not found - States
Error: File not found - History
Error: File not found - Civil
Error: File not found - War -xmp:Subject=1861-1865
Error: File not found - of
Error: File not found - Egypt
    1 image files updated
    6 files weren't updated due to errors

Resulting XMP:
```
 <Iptc4xmpExt:PersonInImage>
	<rdf:Bag>
	   <rdf:li>Hatshepsut -xmp:PersonInImage=Queen</rdf:li>
	</rdf:Bag>
 </Iptc4xmpExt:PersonInImage>

 <dc:subject>
	<rdf:Bag>
	   <rdf:li>United</rdf:li>
	</rdf:Bag>
 </dc:subject>

```

**Comment by hvdwolf** [comment]
I think this is a very valid request. I will put it on my todo list. I will try to get it in the next release, but I can't give a date as I have 3 other changes in the queue as well.
I think I will either:
- create a radiobutton selection for separator indeed like  (",") (";") or (" | "). 
- or I will keep the comma, but allow String+ values surrounded by double quotes, like you propose.

**Comment by emteejay** [comment]
Another option is to use backslash to enter a literal comma \\,
I can see a case where quotes might be wanted in the string.
Note I had to use two backslashes because they are significant in github markdown!

**Comment by mrtngrsbch** [comment]
humm... 
the bash syntax seems very appropriate to me
it is also used comfortably in Open Refine and can accept a CR.
ex.
`echo -e "Hello,\nWorld!"`

**Comment by MetadataDeluxe** [comment]
Thank you very much for considering this request.

A backslash work, but less expert users might make mistakes or forget. It might also slow down data entry - can't just copy and paste.

Another option, which I hesitate to suggest because it might require more coding, is to break up each String+ value into separate text boxes - perhaps a vertical scrolling list with a "+" to add another and a "x" to delete an entry.

**Comment by hvdwolf** [comment]
I will have a look at all options.
The "escaping" of characters is well known on linux systems (and some MacOS users), but less for Windows and most MacOS users. (And I do currently not know how java deals with that kind of string parsing).
The tabular option, which is more like the vertical scrolling list, is also something I'm thinking of as I might reuse code from the custometadatasets.

**Comment by MetadataDeluxe** [comment]
A comma separated string, surrounded with quotes would be consistent with how the ExifTool command would be written. That consistency could be a good thing for users moving between the Edit Data and the ExifTool Commands screens

`exiftool -xmp:Subject="Lincoln, Abraham, 1809-1865"`

A vertical scrolling list could be expanded in the future to allow complex structures. Spoiler alert, this is something I was going to ask for, but I realize it might be out of scope right now.

| Name                       | Culture | ID        | Vocabulary | Role      |   |
|----------------------------|---------|-----------|------------|-----------|---|
| Palladio, Andrea           | Italian | 500021650 | ULAN       | architect | x |
| Bertotti-Scamozzi, Ottavio | Italian | 500006184 | ULAN       | draftsman | x |
|                            |         |           |            |           | + |


Wait, I just discovered something while writing this - exiftool structure commands use a pipe to escape a comma! You can't use quotes. This makes a pipe a bad choice for a list item separator.

see Palladio|, Andrea below:

`
exiftool -config vrae.config -xmp-vrae:WorkagentIndexed="[{name=Palladio|, Andrea, nameVocab=ULAN, nameRefid=500021650, role=[{value=architect}], culture=[{value=Italian}]}]" "C:\Users\Computer User\Pictures\_TEST\bb99328578.jpg"
`

Sorry for going on a tangent with a complex problem I was going to introduce later, but it did uncover something to me about different ways to handle commas (and other punctuation) in a string.

**Comment by hvdwolf** [comment]
Ah! Now I think I know who MetadataDeluxe is :)

**Comment by MetadataDeluxe** [comment]
Confession: my name is Greg Reser and I've been creating Adobe Bridge scripts for VRA Core (Visual Resources Association) for a while. After getting frustrated with new bugs in every Bridge update, I finally dove into ExifTool. @mrtngrsbch encouraged me to look at jExifToolGUI as a UI solution.

**Comment by hvdwolf** [comment]
Hi Greg. Great work you did.

I think the comma separated, quote embedded strings should not be be too difficult.

The pipe symbol is indeed used for structured information (aka hierarchically structured keywords) for others: see [here](https://exiftool.org/struct.html). 
I completely forgot that.

It was anyawy on my todo list, but I kept shifting it backwards (also because it is not in my personal usage, which is relatively simple). 
Your idea of the table like input sounds good. I was still thinking of how to do that.
Of course "some" user should setup the keywords database, and then I should make it possible to import/export that for people around the world.

**Comment by mrtngrsbch** [comment]
> Of course "some" user should setup the keywords database, and then I should make it possible to import/export that for people around the world.

mmm... I understand not much of all this but I have the intuition that I must start learning.
