### ISSUE TITLE
Question about "Load Directory"

### ISSUE THREAD

**Issue by MetadataDeluxe** [hvdwolf/jExifToolGUI#115]
Is "Load Directory" intended to let me select a folder and load all files it contains for viewing/editing?
In Windows 10, "Load Directory", allows me to select a single image file to load.

1. Either clicking the Load Directory icon or going to File > Load Directory
2. "Locate the image folder..." file browser opens
3. Double-click a folder or select and click "Open", it opens and displays the files. I can select a single file to load, but not all files.

![jExifToolGUI_Load_Directory](https://user-images.githubusercontent.com/5862936/116495321-84e2a880-a857-11eb-9424-44967b8aa34d.png)

**Comment by MetadataDeluxe** [comment]
Wait, I got it...

Open the folder > select a file > double click file or click "Open"

I was expecting to select a folder and click "Open". Selecting a file might just be a quirk of the Java filechooser.

**Comment by MetadataDeluxe** [comment]
I guess this is really a feature request... could "Load Directory" open a Select Folder style dialog where only directories are displayed?

For example:
![windows_Load_Directory_01](https://user-images.githubusercontent.com/5862936/116727163-0db52d80-a999-11eb-89f2-c070b9117f08.png)

**Comment by hvdwolf** [comment]
I know exactly what you want and that is the exact java function that is being used (in the most left button): `jchooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);` or [here](https://github.com/hvdwolf/jExifToolGUI/blob/master/src/main/java/org/hvdw/jexiftoolgui/controllers/StandardFileIO.java#L296). The most left button is open folder. The second button is open files.
It should restrict to only folders on Windows and Linux, but Windows 10 is not consistent. MacOS behaves differently anyway as that does not allow this separation. MacOS is designed to have one file/folder option for both (Mac wants to keep it simple for her users). I have no other option than to use the function that "should" do this.

The other option is to choose in the Preferences -> System tab -> select the Awt dialog. This is the old inflexible dialog which allows stricter separation, also on MacOS (against design guidelines).

Note also that JTG supports command line options like (on windows): jexiftoolgui.exe c:\<some folder> and even combinations of (multiple) folders and (multiple) files.
It also supports drag & drop. You can drop files or a folder on JTG.

**Comment by MetadataDeluxe** [comment]
I thought it might a Windows 10 inconsistency. But I see the Awt dialog now and that works. Drag & drop - yes, great!  I'm still exploring JTG and delighted to discover all the things it can do.

By the way, I am not a programmer. I taught myself JavaScript in order to build Bridge scripts, but JTG is on a whole other level! I have been exploring the source code and learning.
