### ISSUE TITLE
Changes to GPS tab

### ISSUE THREAD

**Issue by Sponsoredby** [hvdwolf/jExifToolGUI#167]
is it possible for an additional features? 

when clicking find location, it uses the long and lat coordinates from the image, which you get when selecting (copy from selecting images ) rather than having to type a place name in, which you might not know. 

Also is it possible to decide what data is pulled from the nomanatim lookup

**Comment by hvdwolf** [comment]
Hi,
Useful features are always possible 😉 (unless I can't build it)

I do not exactly know what you mean with your first remark.
It does NOT copy the coordinates from the image which you used for the "copy from selected image".
For the very first load after very first program start, it uses the coordinates from the city where I live.
On every subsequent  "Find Location", it uses the location coordinates from the last search, which are autosaved to the preferences. Not from that "copy from selected image" image.

Or do you mean that you want to use the coordinates from that "copy from selected image" to find the correspeonding location, city, etcetera (if applicable of course)

I don't understand what you mean with which data is pulled from nominatiom lookup. Please give an example.

**Comment by hvdwolf** [comment]
I quickly checked my code and searching on coordinates already works, be it manually.
If you use the "copy from selected", and then manually copy the coordinates in the "Find Location" window, you can search on it.
I will create a button for it to automate it.

Yosemite national park, California
![Screenshot 2021-10-18 19 29 41](https://user-images.githubusercontent.com/4520361/137779375-9e633e88-a800-404e-aff6-a382235fbd79.png)

Sagrada Familia, Barcelona
![Screenshot 2021-10-18 19 35 51](https://user-images.githubusercontent.com/4520361/137780144-ac495892-df80-4762-8d24-b0417a59c519.png)
