### ISSUE TITLE
Translatable text (?)

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#213]
hi,
I can't find in Weblate this string to translate
![ScreenShot 2022-01-11 a las 14 36 33](https://user-images.githubusercontent.com/693328/148993437-8b155b9e-6038-43af-9ede-506d7ad7e551.jpg)

MacOS
JTG v1.10.0

**Comment by hvdwolf** [comment]
You are right. I just added the new string and it is now in weblate
