### ISSUE TITLE
Strange behavior with ExifTool.config

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#219]
I have had a hard time understanding what is going on and I still don't think I do.

1. JTG overwrites my vrae.config file on startup

https://user-images.githubusercontent.com/693328/150656128-f99a3ddd-2142-4142-8254-c1c0b68c9f7a.mp4

2. I can run normally #exiftool -config vrae.config -xmp-vrae:ImageWorktype="toto" AR-MA-Bruzzone-Agesta-Antonella-Je-suis-la-2014-1.jpg
    1 image files updated
3. JTG tells me that this value does not exist.
![image](https://user-images.githubusercontent.com/693328/150656039-053e4eb2-c3ca-41ab-aaba-59c16e0a4d2d.png)

vrae.config
https://github.com/MetadataDeluxe/VRA-Core-Essentials-ExifTool-config/blob/main/vrae.config

**Comment by hvdwolf** [comment]
Yes, unfortunately this is indeed a bug. My check is wrong.
It should be "if not exists ....". but it is doing "if exists .." thereby overwriting the file on every new startup.

**Comment by mrtngrsbch** [comment]
Trying to find the problem I have done many tests. for example: deleting "jexiftoolgui.db".
At that point I remembered that my presets are hosted in the database....
![ScreenShot 2022-01-23 at 15 29 52](https://user-images.githubusercontent.com/693328/150692674-cb3f8f27-5eb7-4c87-a8c8-8bfaa92d9156.jpg)

Doing my tests is that I find improvements to make and old issues... and if you let me I will create a thread with this topic that seems to me very important
