### ISSUE TITLE
Why enums Apple, Microsoft, Linux

### ISSUE THREAD

**Issue by hvdwolf** [hvdwolf/jExifToolGUI#22]
Why are the enums OS_NAMES called Apple, Microsoft, Linux?

I understand the logic of enums, but are these names java standards?
To me they are illogical. The brand is Apple, the os_name os MacOS (not Mac OS/X anymore), the brandname is Microsoft and the os_name is Windows.

And to take this one step further: To me it would be logical to have for example Linux as one enum, with distributions as derived enums (same for windows with win8, win10, etc).

**Comment by Swissbite** [comment]
You can name them as you want. But your strings was neither equal. Once it was Apple, then Windows then Linux. So I used the Brands. The strings where mac/windows /linux but the names of your variables were different.

The benefit of the enums: Rename them with the IDE and everything will still compile/test :-D

**Comment by hvdwolf** [comment]
Sorry, you are right about being me not being consistent :flushed:
Now that I detected I think I will change it.
