### ISSUE TITLE
VRAE ImageWorktype NOK ?

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#220]
Hi @MetadataDeluxe,

I have a problem with writing "xmp:vrae:ImageWorktype" and I don't see the error.
I want to write that tag and I get an error:

JTG:
![ScreenShot 2022-01-23 a las 16 20 08](https://user-images.githubusercontent.com/693328/150694782-a503dc99-0517-40d4-85b8-e85ac69d0477.jpg)

ExifTool:
➜ > exiftool -config vrae.config -xmp-vrae:WorkTitle="" image001.jpg
_Warning: [Minor] Duplicate XMP property: vrae:work.title - image001.jpg_

I am using vra.config [https://github.com/MetadataDeluxe/VRA-Core-Essentials-ExifTool-config]

'image.worktype' => { Name => ImageWorktype, Writable => 'string' },
	
	'image.worktypeIndexed' => {
		Name =>	'ImageWorktypeIndexed',
		List => 'Seq',
		Struct => {
			value => { Writable => 'string' },
			vocab => { Writable => 'string' },
			refid => { Writable => 'string' },
			href => { Writable => 'string' },
			extent => { Writable => 'string' },
			source => { Writable => 'string' },
		},
	},
	
![11 test vrae](https://user-images.githubusercontent.com/693328/150694832-a3268965-d14d-4a68-9425-51fbe1ba6016.jpg)

Please, could you do a test on your side ?

**Comment by mrtngrsbch** [comment]
Hum...
you may have a problem with the ExifTool.config path ?

**Comment by mrtngrsbch** [comment]
Hi @hvdwolf,

Disculpas pero no encuentro donde hablamos de a configuracion de los prsets y exiftool config.
Por favor, podrias decirme brevemente como es el mecanismo para una install clean ?

best

**Comment by MetadataDeluxe** [comment]
@mrtngrsbch I'm having a different problem: I get an error saying there is no image selected. I am sure the image is selected and I have tried different images and folders. I think I must be doing something wrong. I'll keep trying.

![image](https://user-images.githubusercontent.com/5862936/150731903-bbeef138-4ac6-422c-8914-8785ba25f9ae.png)

**Comment by MetadataDeluxe** [comment]
@mrtngrsbch I got around the "no file selected" problem by reading data using the exif setting first, then I was able to read vrae-full. I'll do more testing on this to identify a pattern.

The good news is that I was able to edit Image Worktype.

![image](https://user-images.githubusercontent.com/5862936/150734119-c781d7a9-c3e3-4df0-af0b-c23cabf35727.png)

You may have had a problem that was my fault.
I had not published the updated release v.1.1 on github, so you may have used the old config file.
This is the one I used successfully https://github.com/MetadataDeluxe/VRA-Core-Essentials-ExifTool-config/releases/tag/v.1.1

**Comment by MetadataDeluxe** [comment]
@mrtngrsbch Here is my test image for your confirmation that Image Worktype was added.
![martin_TEST](https://user-images.githubusercontent.com/5862936/150735105-3bda5905-bd44-4e45-a445-cab8f24c4bb9.jpg)

**Comment by mrtngrsbch** [comment]
hummm...

Yes, I've also figured out how to bypass that file selection bug ;-)
Yes, I'm seeing your edit from the command line:
![image](https://user-images.githubusercontent.com/693328/150841013-a0dcd59e-75e5-4531-b884-13de07cafa02.png)

Am I wrong or is version v1.1 the same as https://github.com/MetadataDeluxe/VRA-Core-Essentials-ExifTool-config/blob/v.1.1/vrae.config ? Well I had the latest version from the repository and they look identical.

Something is not working for me and now I think it is my JTG template.
Do you have one? Please, can you compare them?
Here I send you my vrae full preset:
[vrae-full.csv](https://github.com/hvdwolf/jExifToolGUI/files/7927904/vrae-full.csv)

best

**Comment by MetadataDeluxe** [comment]
You are right, the version in the repository is v1.1. You were already using the correct version, I just neglected to update the release link for other users who download from there.

For JTG template, I think you need to change this:
vrae-full	56	Image Work Type *	xmp:vrae:Imageworktype	
to this:
vrae-full	56	Image Work Type *	xmp:vrae:ImageWorktype

**Comment by mrtngrsbch** [comment]
Grrr... Thank you very much Greg!

Sorry, that was one of my many modifications, as I have tried them several times. Now I can see well your TEST in JTG (but I swear I did it before).
I've been through this before but this time strange things have happened that I can't explain even reading the log in debug mode.

I just hope it's not age or alzheimer's.

best

ps: I'm starting to create the metadata of my future Contemporary Art Repository (+2000 works, +500 work agents) in VRA Core 4 with a 'minimal records' + others and I have some questions to ask you that I can't find in the manuals. When I have everything organized I'll send you a detailed email.

**Comment by MetadataDeluxe** [comment]
Don't feel bad, I have had trouble creating a new JTG and connecting it to vrae.config. I ended up editing the built-in vrae-full.
I need to do more trials to see what is happening.

Yes, I will do my best to answer your VRA Core 4 questions.

**Comment by mrtngrsbch** [comment]
The names of the conf files are a bit confusing (vrae.conf, isadg-struct.cfg...) I think we should unify them.
I think it would be very important that JTP has the additional presets incorporated and not only inside the DDBB....
In that sense I will create an issue "feature update" to discuss these issues.
Also an issue to create a Dublin Core editing panel, VRA (full, minimal?), ISADG...

**Comment by hvdwolf** [comment]
Just to make sure whether I did not miss anything after having followed this issue: I don't see anything for me to do here, at least not for the time being. Am I correct?

**Comment by mrtngrsbch** [comment]
> Just to make sure whether I did not miss anything after having followed this issue: I don't see anything for me to do here, at least not for the time being. Am I correct?

You are correct. Nothing for now.
Later I will create a feature request to incorporate some presets to JTG. I think I should review 'from scratch' these templates, the import and export of presets.

**Comment by MetadataDeluxe** [comment]
Is the latest version of vrae.config (v1.1)  being used? This contains 'image.worktype'
https://github.com/MetadataDeluxe/VRA-Core-Essentials-ExifTool-config/blob/main/vrae.config

**Comment by mrtngrsbch** [comment]
yes, yes...
i've already successfully use ' image.worktype'.
thanks
