### ISSUE TITLE
[import/export] XMP:VRAE to CSV > CSV to JPG

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#222]
Hi,

The Import and Export metadata functions I think is one of the most important tasks, although it can be complex.
Evidently this point needs a more detailed review although, without a doubt, many specific tasks can be leave to ExifTool.

What I need:
- Export the XMP metadata (xmp:all, xmp:isadg, xmp:vrae) to .csv & .xmp
- Import XMP metadata (xmp:all, xmp:isadg, xmp:vrae) to .csv to .jpg (or other)

Why is this important?
Editing metadata is tedious and the most practical method I know is to do it in a spreadsheet (where I can use formulas) and with [OpenRefine](https://openrefine.org/), to do massive edits.

![image](https://user-images.githubusercontent.com/693328/152443505-7d9ef8ff-a167-430e-b813-6751808bf6a2.png)

@hvdwolf, please could you tell me where I am wrong, no doubt you have been through this issue before.
To my understanding this problem is in ExifTool > I have searched as much as possible in your forum and I don't think I can find the good answer.

I export to CSV [-xmp-vrae:all] but it exports ALL XMP (not too distressing yet).
`exiftool -xmp-vrae:all -a -csv vrae_exiftool_example.jpg > vrae_exiftool_example.csv`

I import CSV to JPG (previously I modify the first cell of the CSV file: "vrae_exiftool_example.jpg" > "222.jpg")
`exiftool -csv="vrae_exiftool_example.csv" "222.jpg"`
Result = NOK

3 Files:

![vrae_exiftool_example](https://user-images.githubusercontent.com/693328/152447675-d6980cd1-87c3-423f-a5f6-34f92e74309d.jpg)

![222](https://user-images.githubusercontent.com/693328/152447667-ed66024a-c1a1-45d6-aa31-a12113945627.jpg)

[vrae_exiftool_example.csv](https://github.com/hvdwolf/jExifToolGUI/files/7998988/vrae_exiftool_example.csv)

**Comment by hvdwolf** [comment]
Hi,

I missed this completely and already since 4th of February. I am very sorry.

exiftool can export all tags it finds in an image, but it can't import unknown, non-standard tags.
Exiftool needs the vrae config file to be able to import vrae tags.
Please try with `exiftool -config "/path/to/config_file" -csv="vrae_exiftool_example.csv" "222.jpg"`

**Comment by mrtngrsbch** [comment]
Hi, 
Now that I read this post again I wonder in what state of mind I was in... because the answer you have given me I have known since the beginning of the config file Phil's refusal to incorporate it into ExifTool.

Sorry and thanks for your answer. I'm sure it was a day when I was distressed ;-)
