### ISSUE TITLE
MacOS starting issue

### ISSUE THREAD

**Issue by SMarco360** [hvdwolf/jExifToolGUI#224]
- OS: macOS Monterey 12.3
 - Version [linux distro version or windows or MacOS version]
 - Package: [jExifToolGUI-1.10.0-x86_64-macos-with_jre.dmg]

**Describe the bug**
Can't start jExiftoolGui (while Exiftool in Terminal is working). stuck in "not responding"

**To Reproduce**
ExifTool: exiftool 12.4
in: /usr/local/bin/exiftool

Log states permission denied at:
[AWT-EventQueue-0] ERROR o.h.j.controllers.CommandRunner - IOException error java.io.IOException: Cannot run program "/usr/local/bin/lib/Image/ExifTool.pod": error=13, Permission denied
while "everyone" read/write is set.

**Comment by hvdwolf** [comment]
Your error message says: "Cannot run program "/usr/local/bin/lib/Image/ExifTool.pod".
That is correct as the pod file is the documentation file (Plain Old Documentation format).
You need to have "/usr/local/bin/exiftool". That is your exiftool

**Comment by SMarco360** [comment]
??? It's not me calling "/usr/local/bin/lib/Image/ExifTool.pod" it's JExiftoolGUI calling it.

Exiftool is working in cli: 
"which exiftool" in TERMINAL gives me "/usr/local/bin/exiftool" as the /usr/local/bin contains the exiftool executable unix-file and the .pod-file is stolen in "/usr/local/bin/lib/Image/ExifTool.pod".

So from my view: all files where they should be but I don't now why JExifToolGUI is calling "the wrong file"

**Comment by hvdwolf** [comment]
Please go to File -> Preferences -> General and set the correct path to `/usr/local/bin/exiftool`.
I will start searching why JTG automatically selects the pod file. I don't see it right now.

**Comment by SMarco360** [comment]
thanks. But I can't start JExifToolGUI so there is no way to get into the Preferences to correct the path. JExifToolGUI is not responding therefore I copied the exiftool (from /usr/local/bin) to /usr/local/bin/lib/Image and added .pod (as it is called) but still the APP is not responding 

attached you'll find the log (with the "faked exiftool.pod")

(#logback.classic pattern: %d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
20:33:23.043 [main] INFO  org.hvdw.jexiftoolgui.Application - Start application jExifToolGUI
20:33:23.046 [main] INFO  org.hvdw.jexiftoolgui.Application - Continuing in system language or, if not translated, in English
20:33:23.558 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.mainScreen - running on Apple. set correct menu
20:33:24.997 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.mainScreen - string for DB: /Users/marcoschwaer/jexiftoolgui_data/jexiftoolgui.db
20:33:25.000 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.Utils - preference exiftool returned: /usr/local/bin/lib/Image/ExifTool.pod
20:33:25.256 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.Utils - exiftool_found mentions: true
20:33:25.257 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.Utils - exiftool path /usr/local/bin/lib/Image/ExifTool.pod
20:33:25.751 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.mainScreen - OS name APPLE)

complete log with calling the wrong auto-selected exiftool.pod
#logback.classic pattern: %d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
20:28:39.005 [main] INFO  org.hvdw.jexiftoolgui.Application - Start application jExifToolGUI
20:28:39.007 [main] INFO  org.hvdw.jexiftoolgui.Application - Continuing in system language or, if not translated, in English
20:28:39.385 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.mainScreen - running on Apple. set correct menu
20:28:40.356 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.mainScreen - string for DB: /Users/marcoschwaer/jexiftoolgui_data/jexiftoolgui.db
20:28:40.358 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.Utils - preference exiftool returned: /usr/local/bin/lib/Image/ExifTool.pod
20:28:40.366 [AWT-EventQueue-0] ERROR o.h.j.controllers.CommandRunner - IOException error java.io.IOException: Cannot run program "/usr/local/bin/lib/Image/ExifTool.pod": error=13, Permission denied
20:28:40.368 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.Utils - exiftool_found mentions: true
20:28:40.368 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.Utils - exiftool path /usr/local/bin/lib/Image/ExifTool.pod
20:28:40.747 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.mainScreen - OS name APPLE
20:28:40.750 [AWT-EventQueue-0] ERROR o.h.j.controllers.CommandRunner - IOException error java.io.IOException: Cannot run program "/usr/local/bin/lib/Image/ExifTool.pod": error=13, Permission denied

**Comment by hvdwolf** [comment]
as a work-around: please try to remove your settings and start "fresh".
From a terminal please do "rm ~/Library/Preferences/org.hvdw.jexiftoolgui.plist" and see if it selects the correct exiftool when restarting.

**Comment by SMarco360** [comment]
great! Thanks a lot - working now.
