### ISSUE TITLE
Just recover the creation date of Google Photo pics

### ISSUE THREAD

**Issue by alesis100** [hvdwolf/jExifToolGUI#227]
When I download the pics from Google Photo, they have all the same date, the date and hour when I downloaded them. I know they are on the exif data, because it is inside but I dedicated a few hours without results. I just want to add a folder with many photos or movies and export them with a correct creation time so I can find them and archive them better. Thank you very much.
I don´t know why Google has changed this, a pair years ago it worked perfect.

**Comment by hvdwolf** [comment]
This is easy.
- Unzip your downloaded google photos zip to some folder
- In jExifToolGUI load all images and select them all
- From the menu: "Date/Time" -> "Set file date to DateTimeOriginal" (3rd option)

Now all your images will have the orginal date/time when you shot the images
