### ISSUE TITLE
How to hide the product name and version number?

### ISSUE THREAD

**Issue by xx13295** [hvdwolf/jExifToolGUI#233]
![image](https://user-images.githubusercontent.com/27811560/167243385-478e4e61-26ad-4cee-a3d3-8a82c2938aff.png)
![image](https://user-images.githubusercontent.com/27811560/167243408-5767f5ea-9e40-46bb-b824-43924eecc3ac.png)
![image](https://user-images.githubusercontent.com/27811560/167243416-4a0d64d8-4105-4812-8047-b13a3cc3ec09.png)
如何隐藏掉以上内容，并不想让其他人知道是通过软件修改的。

How to hide the product name and version number?
I don't want others to know that I modified the picture through the software.
Thank you！

**Comment by hvdwolf** [comment]
You can't. 
exiftool is really completely impossible. It is not even allowed to modify the exiftool source code to do this.
I will not remove my "jExifToolGUI x.y.z" version stamp either. It is my software that you are using (for no price at all) and it will stay in there.
Your only option is not using exiftool and not using my software.
Note that all other imaging packages do exactly the same (and also MS word, excel, Adobe, etcetera)
