### ISSUE TITLE
Install in MacOS 12.3.1 & M1

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#242]
La instalación de JTG 2.0.1 
monta el disco correctamente, pero no abre la carpeta con los archivos de la aplicación

https://user-images.githubusercontent.com/693328/169707581-e041043e-f304-4b45-9e26-be3225f038c6.mp4

Apple M1 Pro
MacOS 12.3.1 Monterrey

**Comment by hvdwolf** [comment]
Thanks for reporting.
I will look into it.

**Comment by mrtngrsbch** [comment]
acabo de probar con 
MacOS 10..15.7 Catalina 
y es el mismo resultado

**Comment by mrtngrsbch** [comment]
mmm... cuando ejecuto 'jExifToolGUI-x86_64-macos-2.0.1-with_jre.dmg' NO se abre una ventana nueva con el link a Aplicaciones, jExifToolGUI.app y LICENCE, sino que simplemnte se monta el disco. Personalmente no es un 'problema', pero quizá sea poco intuitivo para otros usuarios.

![image](https://user-images.githubusercontent.com/693328/173901395-56d79e64-5fea-4616-9f6b-ae25d7213ab3.png)


Apple M1 Pro
MacOS 12.3.1 Monterrey
