### ISSUE TITLE
Volumes access NOK ?

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#243]
JTG 2.0.1
No access to mounted volumes 
![ScreenShot 2022-05-22 a las 14 07 41](https://user-images.githubusercontent.com/693328/169708363-020ccc13-b9ff-4514-81ce-3fd287b78b0f.jpg)

Does not display Drive volume files
![ScreenShot 2022-05-22 a las 14 07 54](https://user-images.githubusercontent.com/693328/169708370-ec020ccd-dbeb-4602-a9c0-c8e462e4b382.jpg)

I note that the access permissions are well granted.
![ScreenShot 2022-05-22 a las 14 01 00](https://user-images.githubusercontent.com/693328/169708396-f6da79f6-fbe0-4393-a4b7-ed98bc4c18ae.jpg)

Apple M1 Pro
12.3.1 Monterrey

**Comment by mrtngrsbch** [comment]
I just tested with 
MacOS 10.15.7 Catalina
and it DOES work = has access to volumes

**Comment by hvdwolf** [comment]
It should have access. There are special entries in the Info.plist of a bundle for network Volumes and USB/SD-card Volumes that state that the applications wants access. 
The very first time, MacOS should show a popup and ask if access is allowed, but once the application has been granted access it should "simply" continue to function.

**Comment by mrtngrsbch** [comment]
No problem. Then it will be logged as a 'problem' with Google Drive.
