### ISSUE TITLE
Commandline can't handle spaces in path

### ISSUE THREAD

**Issue by Key-Snapper** [hvdwolf/jExifToolGUI#245]
**Version (please complete the following information):**
 - OS: Linux
 - Version: Linux Mint Cinnamon 20.3
 - Package:  appimage 2.0.1
**Describe the bug**
The command line does not accept space in path.
This is true for manually selected pics (empty path field) and with the path field filled with the "browse" button.

![Bildschirmfoto jExiftooGui](https://user-images.githubusercontent.com/84930208/170990193-6b3bf713-f94d-47ca-92bf-801f50a40663.png)
![Bildschirmfoto jExiftooGui2](https://user-images.githubusercontent.com/84930208/170990206-cd797532-f1d9-4138-86d7-ad225cedd02c.png)

The command line works, if the path is enclosed in quotationmarks!

Edited: wrong translation

**Comment by peturdainn** [comment]
Same fir the rename function - fails if the path has spaces

**Comment by hvdwolf** [comment]
Fixed for renaming for all platforms.
Exiftool Commands is fixed for Linux/MacOS, still not fixed for windows.

**Comment by hvdwolf** [comment]
I completely rewrote the Windows part to fix this
