### ISSUE TITLE
View Data panel add chars to field ?

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#254]
Hi

I see that the View Data panel adds certain characters to TAGS, which I don't see in ExifTool. 

![ScreenShot 2022-06-24 a las 22 30 09](https://user-images.githubusercontent.com/693328/175753295-fcee44fe-797e-4cfd-80a3-4732a379b922.jpg)

![ScreenShot 2022-06-24 a las 22 30 53](https://user-images.githubusercontent.com/693328/175753293-0485acd1-8ef4-40cd-8579-e005106a7ed0.jpg)

![AR-MA-Bruzzone-Agentes-CIA-018-Taller-Que-hacer-con-los-billetes-de-2-pesos-1654-00](https://user-images.githubusercontent.com/693328/175753378-bf9983ac-03bf-494b-872e-1a1b3369f61a.jpg)

MacOS 12.4 Monterey in M1

**Comment by hvdwolf** [comment]
Some tags contain of string+ or structs. The string+ can contain several strings.
xmp-dc:contributor could contain ["James T. Kirk", "mr. Spock", "Dr. McCoy", "Uhura"]

Exiftool removes the brackets before writing. Maybe I should convert every value to string before writing to screen.

**Comment by mrtngrsbch** [comment]
Thanks Harry, very well explained !
In my opinion, I think we should inherit the capabilities of ExifTool, for the simple fact of not chaining discrepancies. What do you think?

**Comment by hvdwolf** [comment]
😄  I already created this about a year ago, but completely forgot.
Exiftool gives you the option to "Enable output of structured info".
It is under Preferences -> System -> (checkbox) "Enable output of structured info".
If you enable the checkbox, you see those square brackets. If you disable it, you see the default "flat string" output of exiftool. Also in JTG.

**Comment by mrtngrsbch** [comment]
OMG !
I had completely forgotten about it too !
😸
