### ISSUE TITLE
double extensions when renaming with original filename as suffix

### ISSUE THREAD

**Issue by peturdainn** [hvdwolf/jExifToolGUI#256]
I tried renaming a folder with .MP4 and .JPG on (Debian) linux, with following settings:

- prefix = date_time
- suffix = original filename

the result was that all files were renamed correctly but the extension doubled, so .MP4.MP4 and .JPG.JPG

**Comment by hvdwolf** [comment]
Sorry. This was incorrectly closed

**Comment by hvdwolf** [comment]
Fixed in development tree.
