### ISSUE TITLE
Apple Sillicon native support

### ISSUE THREAD

**Issue by anonymousaga** [hvdwolf/jExifToolGUI#258]
Is it possible to get the darwin app to run natively on Apple silicon? I believe this would just mean changing the JDK to an apple silicon compatible one & publishing a darwin arm64 app. Thanks in advance! I also love the new logo.

One example of a JRE supporting native apple silicon is adoptopenjdk-jre-11.0.15+10

**Comment by hvdwolf** [comment]
I will have a look at it. It must be possible but I do not have an M1 and can't test myself.

**Comment by hvdwolf** [comment]
You can download a zip from [here](https://mega.nz/file/JcVWmITR#vUSrvb9hje5_2qannf_GXQrkRGASfknC5C0JaGCjUBE). It contains the bundled app. Please try.

@mrtngrsbch : Can you try it on your M1 as well?

**Comment by mrtngrsbch** [comment]
The application starts correctly BUT... I just found a bug that I had not seen before in the 201 version, because I normally use drag&drop
and that is that it does not open the images in a folder ;-(

i.e.: my macOS version and this bundled app have the same bug


**JFilechooser**

https://user-images.githubusercontent.com/693328/180044452-98c67f29-f626-4fc1-9286-23933ddf5355.mp4


**AWT-File dialog**

https://user-images.githubusercontent.com/693328/180044474-a27ab563-1eec-4d26-97a8-b2ef1b32fa18.mp4

**Comment by hvdwolf** [comment]
Strange. That is exactly what I did. I took the bottom one from https://adoptium.net/temurin/releases/?version=11
![Screenshot 2022-07-20 19 18 40](https://user-images.githubusercontent.com/4520361/180043607-ebdf1a0e-fb83-4f76-84d3-488b0cd90a89.png)

I just did it again to make sure I did not make a stupif error in my scripts.
Please try again.
https://mega.nz/file/0AkDSbQY#5WycWyhMZkNotSxVIR9cR5ZrLUHX7OjhYM2H-6z5-fY

**Comment by anonymousaga** [comment]
@hvdwolf yes, it works now. Looking in, the original aarch64 app used the VM adoptopenjdk, while the new app uses temerium VM. Now your new app is working with aarch64. I think you can post this now. The drag&drop works fine when I used the correct icons.

**Comment by hvdwolf** [comment]
Thanks. 
I still need to do some bugfixing before a 2.0.2 release. Then I will also publish the aarch64 dmg.

**Comment by mrtngrsbch** [comment]
> You are using the wrong icon. The first icon is a folder and is to simply select a folder containing images. It does not show images or file types as you select a folder (containing images). JTG will then read all images inside that folder. The second icon is the file selection button. There you can select 3, 5 or x number of images from a folder containing (x+n) images..

I'm sorry for the unclear message.
In M1 I have problems to open certain folders and I don't know if it is JTG or a permissions problem. I have cleared cache and regenerated permissions and I do not see where the problem is, but certain folders do not show me the inside of them.
For example, the Download, desktop or Pictures folder does not open the content, but I can open an image inside it.

see this video

https://user-images.githubusercontent.com/693328/180057985-f45893b1-56d8-44d4-9432-d92ac8ee5946.mp4

**Comment by anonymousaga** [comment]
im wondering when 2.0.2 is coming out? No worries for getting it done, I'm just curious for an ETA

**Comment by mrtngrsbch** [comment]
Honestly, I haven't discovered where the problem lies and am currently content opening the images with a drag & drop.
It's not a very comfortable solution but it doesn't disable me to use JTG either.

Much worse is the inconvenience of not having a M1 version of VirtualBox.

**Comment by anonymousaga** [comment]
Actually, there is. I can make you a qemu virtual machine that runs m1 & send the command that runs it.

**Comment by anonymousaga** [comment]
You can try UTM. It is a GUI frontend of QEMU for macos. It supports virtualization through qemu aarch64 virt, as well as emulating an intel cpu. I have used UTM to install windows 11 for arm on my m1 mac without paying for paralells. Its free, but the app store is how it gets donations ($10 on app store, free otherwise). I migrated all  my VMs of old versions of windows, all running on virtualbox, to UTM successfully for my m1 mac. The big difference is that its emulation, so every instruction has to be converted, slowing down the guest OS a lot. Still, it wasnt very noticeable because i came from an old imac that could barely run imovie to a m1 pro that is too overkill for me.

**Comment by mrtngrsbch** [comment]
great, it sounds very interesting and I didn't know it. I'm putting it on my list right now to try it out. Many thanks for the advice

**Comment by anonymousaga** [comment]
Do you want any specific OS? I have a lot of configs already made.

**Comment by mrtngrsbch** [comment]
cool, windows 10, last MacOS Intel version & last ubuntu. many thanks

**Comment by anonymousaga** [comment]
Oh! You dont even need my configs. See the [UTM Gallery](https://mac.getutm.app/gallery/) for windows & ubuntu. Arm windows 10 isos dont exist anymore, so use emulated windows 10 x86 or windows 11 arm. For macos intel, see this great github repo, which i used for some of my vms. https://github.com/adespoton/utmconfigs
