### ISSUE TITLE
Error "no images selected" when exporting metadata, even though there are

### ISSUE THREAD

**Issue by PhotoJoseph** [hvdwolf/jExifToolGUI#273]
Running macOS 12.4, Intel, Java 1.0 (11.0.10) (and I just ran Java 8 Update 351 to be sure). jExifToolGUI is 2.0.1

The majority of the time that I select video files to export metadata from, I get an error "no images selected; nothing to work on". As you can see in the screenshot, the files are clearly selected. The only thing that seems to make this work is to select them and open Compare, and then the software realizes they are actually selected. 

Also I have no idea why sometimes it's in icon view and sometimes it's in list view. It doesn't seem to matter how many or few are imported!

![CleanShot 2022-10-24 at 17 35 00@2x](https://user-images.githubusercontent.com/78106443/197659961-517a99c4-a33e-4a9a-a9ca-4026432200ef.png)

**Comment by hvdwolf** [comment]
Definitely a bug that needs to be fixed.

**Comment by PhotoJoseph** [comment]
OK thanks

**Comment by PhotoJoseph** [comment]
I just installed on Windows and am seeing the same "no images selected" error here. Until it's fixed, is there a workaround? Even doing the compare doesn't always trigger it, and when I do this for real it'll be to hundreds of clips so running a compare probably isn't ideal.

**Comment by hvdwolf** [comment]
Yes, this is a general bug. I mentioned that it worked on linux and windows for the re-ordering of rows in the custom section.
It is indeed quite annoying.
The only work-around currently is to copy the images to some folder and open that folder, instead of opening files.

**Comment by PhotoJoseph** [comment]
opening the entire folder works? Perfect, I'll do it that way. Thank you.

**Comment by PhotoJoseph** [comment]
FYI importing an entire folder does not necessarily work around the "no images selected" issue, unfortunately (tested on Windows).

**Comment by hvdwolf** [comment]
Which one did you use?
You should not use the one from the menu or the to-left icon.
In the first post you have a screenshot. In that screenshot you see on the right side in the top of that tab also a "Use all images in this folder". These will be automatically selected.

**Comment by PhotoJoseph** [comment]
I have discovered that since the post. Using that feature to define a path works great. Adding images the the window on the left, any way I do it, does not. Good to know, thank you.

**Comment by hvdwolf** [comment]
I fixed it now in the development tree. Will be released in time.

>
>I have discovered that since the post. Using that feature to define a path works great. 
>
It is also faster. On a few images you don't notice it. On folders with more than 25 images up to hundreds, it can become 2-10X as fast (10X in case of 300+ images)

**Comment by PhotoJoseph** [comment]
Oh that's awesome. So you know, I've just recorded a tutorial on extracting metadata from video clips for importing into Resolve. I mentioned this bug and also how to reset the database, but I'll add a text line that explains that bug has been fixed or edit it out if I can. I'll let you know when the video is up!

**Comment by PhotoJoseph** [comment]
yep, understood!
