### ISSUE TITLE
jExifToolGUI.jar v2.0.1 does not run on Windows 10

### ISSUE THREAD

**Issue by gaiking-uk** [hvdwolf/jExifToolGUI#276]
## Issue

**System info**
 - OS: Windows 10 Pro
 - Version: 22H2 [19045.2193]
 - Package jExifToolGUI.jar

**Bug description**
I installed the latest JRE (currently Version 8 Update 351, Released: 18 October 2022) and tried to run `jExifToolGUI.jar`. The splash screen loads however I then get the following error message...
- **ERROR:** Error: A JNI error has occurred, please check your installation and try again.
- **DESCRIPTION:** Exception in thread "main" java.lang.UnsupportedClassVersionError: org/hvdw/jexiftoolgui/Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**To Reproduce**
1. Install [latest JRE](https://www.java.com/en/download)
2. Download [jExifToolGUI.jar](https://github.com/hvdwolf/jExifToolGUI/releases/download/2.0.1/jExifToolGUI.jar)
3. Run `java -jar jExifToolGUI.jar &`

***

## Questions
> Note: There is the java JDK (Java Development Kit) and java JRE (Java Runtime Environment). The JRE is needed to run java applications and is normally 4-5 times smaller than the full JDK. **Since a few years the JREs are no longer distributed**
1. I am confused when you say the JRE is no longer distributed 🤔 -- I have been downloading the JRE form java.com for many years, is this not right(!?)
> This version should run on any system that comes included with **java 11** or newer or where you can install java 11 or newer.
2. Also, just to check -- when you say "Java 11", is this the JRE [Java Runtime Environment] or the JDK [Java Development Kit]?... AFAIK, the [latest JRE is version 8 (351)](https://www.java.com/en/download) and the [latest JDK is 19.0.1](https://www.oracle.com/java/technologies/downloads/#jdk19-windows)... Does jExifToolGUI.jar work with JRE?

Apologies if any of the above sounds strange - I have limited experience with Java, thanks in advance!

***

## Screenshots

![jExifToolGUI jar Error -- 2  command line](https://user-images.githubusercontent.com/37931190/198965795-960074f0-52e0-42bb-b2ff-2fe4e969c1f8.jpg)
![jExifToolGUI jar Error -- 1  double-click](https://user-images.githubusercontent.com/37931190/198965796-e38b452d-ffaf-46a8-a0b5-c9e8422925ec.jpg)

**Comment by hvdwolf** [comment]
Since release 2.0 java version 8 is no longer supported. It is already out of support since 2013 and I stopped supporting it too, as explained on the Release page.
Please download java Version 11 or newer. Then the application will work.
The old Version 8 JRE is still available, but there is no JRE for the newer versions if you download from Sun/Java.
But you are right: the description could be clearer so I changed it on the Releases page https://github.com/hvdwolf/jExifToolGUI/releases
