### ISSUE TITLE
ExifTool Commands panel > Help window []

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#281]
All versions
jExifToolGUI fulfils its mission very well and also gives us the opportunity to use the ExifTool commands in a window.
On several occasions it is necessary to call upon the ExifTool commands | It would be very useful to have a small collection of them at hand in the 'Help' window. 
For example:
`"-AllDates=2023:01:01 11:59:23`  
**But I think it would also be handy to have some interesting links**, for example: [https://github.com/jonkeren/Exiftool-Commands](https://github.com/jonkeren/Exiftool-Commands)

ref.: https://github.com/hvdwolf/jExifToolGUI/issues/280

![image](https://user-images.githubusercontent.com/693328/210440578-c8689d53-5021-4a23-ba57-0e919d24774d.png)

many thanks @hvdwolf

**Comment by hvdwolf** [comment]
I added the link to the help text on Weblate.
