### ISSUE TITLE
Search through metadata - reload images has path twice

### ISSUE THREAD

**Issue by githlp** [hvdwolf/jExifToolGUI#286]
**Version (please complete the following information):**
 - OS: Arch
 - Version: latest
 - Package: yay aur package v. 2.0.0

**Describe the bug**
Search through metadata for keyword is done and the matching pictures are listed the reload images function lists the resulting pictures but adds the path therefor no metadata can be viewed/edited on that selection.

**To Reproduce**
1. Load Directory /home/ronald/pictures/photonew/
2. Search through metadata for keyword is done -> matching pictures are listed 
3. Click on 'Reload these images' Button
4. Select one of those (filtered) images
5. In the View Data tab "ExifTool | Error | Invalid Metadata"
    as the path is shown as **/home/ronald/home/ronald/** pictures/photonew/pic_1.jpg

**Comment by mrtngrsbch** [comment]
I have v2.0.1 on MacOS M1 and I get the same error ;-(

**Comment by hvdwolf** [comment]
Same on Debian. I will look into it.

**Comment by hvdwolf** [comment]
I fixed it in the repository. I now hope to (finally) release a new version within 2 weeks.
