### ISSUE TITLE
Using optional instead of null if there is no value

### ISSUE THREAD

**Issue by Swissbite** [hvdwolf/jExifToolGUI#29]
As an example on the user settings: We are currently using null for no value. But it would be better and less error-prone if we use the Optional Type, introduced in Java 1.8.

As an example, the preferences facade interface would then look like:
```java

public interface IPreferencesFacade {
    enum PreferenceKey { /* ... */  }

    boolean keyIsSet(PreferenceKey key);

    Optional<String> getByKey(PreferenceKey key);
    String getByKey(PreferenceKey key, String defaultValue);
    boolean getByKey(PreferenceKey key, boolean defaultValue);
    void storeByKey(PreferenceKey key, String value);
    void storeByKey(PreferenceKey key, boolean value);

    IPreferencesFacade defaultInstance = PreferencesFacade.thisFacade;
}
```

The benefit: If null, it is an error. If empty or present, the Optional can be asked:

```java
  @Override
    public Optional<String> getByKey(PreferenceKey key) { return Optional.ofNullable(rootNode.get(key.key, null));
    }

public boolean keyIsSet(PreferenceKey key) {
        return getByKey(key).isPresent();
    }
```
With this approach, null pointer exceptions (NPE) are a real issue and not just a value which was not thought about that it may not be present.

**Comment by Swissbite** [comment]
Priority: LOW

**Comment by hvdwolf** [comment]
I do not understand. If the program is "installed" and started for the first time, there are no preferences.
Which means a "null" and then we create an empty one.

You state "_The benefit: If null, it is an error. If empty or present, the Optional can be asked_:"
if null -> Does the program generate an error or still create an empty preference --> First is not OK (I think), 2nd is OK
If empty -> it does exist but is not filled, so a default optional can be provided. --> OK with me.
If present -> the optional can be asked ?? --> Why? If present we do not need the optional

**Comment by Swissbite** [comment]
I've seen too much code (not your project) where someone assumes that the result is always a valid object and does not check if the return value is null. With `Optional`, you have a contract that the Object must be an `Optional` instance where the value is either empty or present.

Method signatures should always be as informative as possible, therefore if a method returns an object, it should have the object and not a null value. If the return value could be empty, then `Optional` is a much better approach to solve such issues. So every consumer of the method knows that the value is optional.
