### ISSUE TITLE
Make this project clonable and openable for IntelliJ IDEA

### ISSUE THREAD

**Issue by Swissbite** [hvdwolf/jExifToolGUI#3]
I just cloned the project, and if I open it directly with IntelliJ IDEA, it does not have the needed information to show the project structure.

There are the following missing files:
- .idea/modules.xml
- .idea/misc.xml

**Comment by hvdwolf** [comment]
Thanks. 
So that is the reason I did not see that when opening the project in IntelliJ on Windows.
