### ISSUE TITLE
arch linux

### ISSUE THREAD

**Issue by zoe12345** [hvdwolf/jExifToolGUI#30]
Hello, thank you for your job !
I want to customize packagedeb.sh so that it could be installed on arch linux.
I probably missed something, but in the line :
cp ../../build/libs/jExifToolGUI-all.jar ./jExifToolGUI.jar
I did not find where is the file 
../../build/libs/jExifToolGUI-all.jar 

In the source-tree, I do not see any directory named build/libs

Sorry if my question is very newbee…

**Comment by hvdwolf** [comment]
You will only find that folder/file after you have successfully compiled a fatJar with everything in it.The "build" directory is created on a "build" run.

I currently know nothing of ARCH linux. When I have time I will look into it and see if "something simple" can be created.

**Comment by zoe12345** [comment]
Sorry again for that newbee's question.
What is the command for compile ? I am not experienced in java…
Just give me the command, I will dig it for customizing to arch linux

**Comment by zoe12345** [comment]
Does we use gradle for compile ?

**Comment by zoe12345** [comment]
So, I helped myself, sorry for the noise. Anyway, your help would be wellcome.
I ran this command :
./gradlew buildDependents
and the output was :
> Task :compileJava
Note: /tmp/jExifToolGUI/src/main/java/org/hvdw/jexiftoolgui/mainScreen.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :processResources
> Task :classes
> Task :jar
> Task :startScripts
> Task :distTar
> Task :distZip
> Task :shadowJar
> Task :startShadowScripts
> Task :shadowDistTar
> Task :shadowDistZip
> Task :assemble
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
> Task :check
> Task :build
> Task :buildDependents

BUILD SUCCESSFUL in 9s
13 actionable tasks: 13 executed

**Comment by zoe12345** [comment]
High !
Now, jexiftoolgui is fully functional, in archlinux.
Here is the link :
https://aur.archlinux.org/packages/jexiftoolgui
Thank you for your job

**Comment by hvdwolf** [comment]
Thanks a lot. Note that at this moment it is a work in process. After I finished the first V1.0 I will switch to a release policy.
