### ISSUE TITLE
Fail to run

### ISSUE THREAD

**Issue by core45** [hvdwolf/jExifToolGUI#31]
Hi, 
I'm trying to run the program but getting the error:
Error running 'All in jExifToolGUI': No junit.jar

What I've done is:
1. downloaded the zip, unpacked it and opened with InteliJ IDEA Community
2. InteliJ installed couple of things
3. I changed the settings as in readme Goto: Settings -> Editor -> GUI Designer and set Generate GUI into: Java source code

Unfortunately it was not enough. What did I do wrong?

I use Ubuntu Linux 18.04 and
IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-45-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 12
Registry: 
Non-Bundled Plugins:

**Comment by hvdwolf** [comment]
The junit.jar is for testing.
I work on GalliumOS, which is a derivative of Ubuntu 18.04 especially for chromebooks.
I am also using IntelliJ IDEA 2019.3.4 (Community Edition)
If I check my project settings at libraries, I have this.
![junit](https://user-images.githubusercontent.com/4520361/78253920-70699a80-74f5-11ea-92df-bfd107b2f902.JPG)

Today I installed it on a windows 10 laptop and it simply works. That doesn't help you, but I currently do not know how to help you.  I have to further check on it.

The only thing: If I do a "find . -name junit.jar" on both my linux and windows laptop, I find inside the idea folder "`/idea-IC-193.6494.35/lib/junit.jar`".
Not on any other location.

To also check:
Please cd into the terminal inside the jExiftoolGUI folder and do a:
`./gradlew assemble buildDependents shadowJar shadowDistZip`

And if it gives an error, please try:
`./gradlew -x test assemble buildDependents shadowJar shadowDistZip`
This will compile without doing the tests.
