### ISSUE TITLE
Edit Data tabs problems

### ISSUE THREAD

**Issue by emteejay** [hvdwolf/jExifToolGUI#32]
Entry boxes for GPS data much bigger than needed, those for XMP/IPTC location are rather small, I suggest moving the buttons  level to the GPS boxes. 

Copying data from selected image clears boxes when a tag is not present in an image, and prevents "Copy Defaults" reloading boxes.

**Comment by hvdwolf** [comment]
I will change it for next release

**Comment by hvdwolf** [comment]
2nd remark: "Copying data from selected image clears boxes when a tag is not present in an image, and prevents "Copy Defaults" reloading boxes."

I clear the fields on purpose. To make sure that no "old" data is left in the fields that gets written to the images by accident.

**Comment by emteejay** [comment]
Clearing the fields is a reasonable design decision but it should not stop the "Copy Defaults" button working.

**Comment by hvdwolf** [comment]
To be honest: The Copy Defaults is not active at the moment. It should copy the Artist/Creator and Copyright field back in, when somehow overwritten.

Based on your answers/comments I have the idea you expected something else from this "Copy Defaults"?

**Comment by emteejay** [comment]
I expect it to copy the relevant fields set in the preferences (currently Artist/Creator and Copyright), these are pre-loaded  when you first open the edit tabs but cleared when the image data is copied. I await the button being made active.
A thought: have the "save" tick boxes disabled by default and automatically enabled if an entry is made in the corresponding field.

**Comment by hvdwolf** [comment]
It does copy it now (should be in next release).

I realy like the idea of those automatically enabled checkboxes, but it requires a listener on every JTextfield. That requires quite some listeners.
