### ISSUE TITLE
Images on command line not handled

### ISSUE THREAD

**Issue by emteejay** [hvdwolf/jExifToolGUI#33]
Loading images listed on the command line would allow integration with file managers.
Drag and drop of images would be useful.

**Comment by hvdwolf** [comment]
I will put it on my ToDo list, but it might take a little longer.

**Comment by agriggio** [comment]
Hi, here's another vote for this, it would be really nice to have.

**Comment by hvdwolf** [comment]
I am looking into it.
I will not work with a MacOS app bundle as app bundles do not support command line parameters.
So for the jar, appimage, the windows executable and the linux deb version.
But currently I am working on the Gui

**Comment by hvdwolf** [comment]
Add command line parameters/arguments handling. Supports (multiple) folder(s), multiple file(s) and combinations. Supports releative paths and symbolic links (Linux/MacOS). **Note:** The MacOS app bundle does not support command line arguments as Apple is really picky on this.
Does NOT support recursively parsing sub-directories as that could lead to tens of thousands of files which might not be a problem for a commandline tool, but is a problem for a Gui needing to load the files.

Examples: 
`java -jar jExifToolGUI.jar ../../Pictures/Summer2015  a.jpg  b.png  /home/pipodeclown/screenshots/*.jpg  ../c.cr2  d.nef`

`jExifToolGUI.exe Pictures\Malaga2012 c:\tmp\pics\*.jpg c:\tmp\pics\*.RAF a.jpg d:\stuff\b.jpg`


To be released in 1.7
