### ISSUE TITLE
Can't access removable volume in Catalina

### ISSUE THREAD

**Issue by ggbalcal** [hvdwolf/jExifToolGUI#34]
Try to access photos stored in the removable disk. MacOS is 10.15.6. jExifToolGUI is 1.3.0. 

I can't see any directory or files when I tried to load directory or images from the removable volume. I guess it is because Catalina doesn't allow access unless explicitly granted. So I went to the privacy/files and folders, the jExifToolGUI is not listed there although pyExifToolGUI is listed which I also have it. 

In any way, we can make jExifToolGUI listed in the privacy setting as well so we can grant access to it?

**Comment by ggbalcal** [comment]
BTW, even if I granted it the "Full disk Access", jExifToolGUI still can't see the directories/files in a removable volume.

**Comment by hvdwolf** [comment]
I will have a look at it. I have an older macbook and can't upgrade above 10.11.

When googling on this I find multiple programs having this issue.
Please open a terminal and try `/Applications/jExifToolGUI.app/Contents/MacOS/jexiftoolgui &`

Please also check if java needs the "Full disk Access"

**Comment by ggbalcal** [comment]
Using the command line works. Thanks for the workaround. 

Java has the removable volume access. But I am using the jre version of the dmg which carries its own jre. So not sure the "java" there will cover the one in the dmg or the one pre-installed in MacOS.

**Comment by hvdwolf** [comment]
This is due to the stupid Apple measures. For a "real" app that is based on java, they want java 1.6 to be installed, next to the java version needed for the app. On all the later MacOS versions this java 1.6 is no longer delivered, and Apple "hides" the download of it. That is why I ranted about Apple and made a not 100% standard bundle.

If you right-click on an app, you can show its contents.
If you go in the finder to `/Applications/jExifToolGUI.app/Contents/MacOS/jexiftoolgui`
and/or likewise to: `/Applications/jExifToolGUI.app/Contents/MacOS/jre/Contents/Home/bin/java`

Can you try to give the `jexiftoolgui` script and/or the `java` binary "Full Disk access" and see if that helps?

If so I need to think of something to trigger that from inside the app. It can't be done automatically as that is against the security measures, but maybe I can open the admin screen with my app selected, so that the user can then decide whether he/she wants to give the app access.

**Comment by ggbalcal** [comment]
No, unfortunately, that didn't work. I dragged both into the full disk access and it didn't work.

**Comment by hvdwolf** [comment]
Hi,

Please try this 1.3.1 version from my Google drive. See if you can add it somehow to the "Full Disk access". It is build slighlty different.
https://drive.google.com/file/d/1Us51ptt0Wn-mH4AMO3d9NhBY2i1WFgHT/view?usp=sharing
Unfortunately I can't test this myself.

As a "bonus": You can also configure a RAW image viewer under Preferences (of course if you have installed one.) It works fine for me, but another tester would be nice.

**Comment by ggbalcal** [comment]
Hi,

I tried this. Unfortunately, it still didn't work. Still the same that it works in either CLI or run the jexiftoolgui withing the package in the finder. 

One more thing I noticed and wanted to see whether you can improve. Today, when I loaded a directory and click the button again for next directory, it doesn't remember the one I chose last time. It forces me to have multiple clicks in order to go to the same parent directory every time (since it is in the external volume not under home directory). Is that possible that it can remember the last selected directory? 

Regardless, this tool (including pyexiftool) has been an awesome tool. And the java version is a big improvement from the python one. I particularly like the reference tab which is very helpful.

**Comment by ggbalcal** [comment]
One more thing to ask. Is there a way to preview the thumbnail of HEIC?

**Comment by hvdwolf** [comment]
> One more thing I noticed and wanted to see whether you can improve. Today, when I loaded a directory and click the button again for next directory, it doesn't remember the one I chose last time. It forces me to have multiple clicks in order to go to the same parent directory every time (since it is in the external volume not under home directory). Is that possible that it can remember the last selected directory?

In Preferences you can set a default directory, and a  "always use last opened folder".

> One more thing to ask. Is there a way to preview the thumbnail of HEIC?

I just stumbled on that format a few days ago, and it is a IOS11+ and High Sierra+ format. I have to look at that.

**Comment by hvdwolf** [comment]
I now use sips to convert the heic images to preview jpgs. Please test below test version.
On my Google drive: 
full app: https://drive.google.com/file/d/1wThLcr3eTIG4t5G0PAcKa4Nc4Y026X8z/view?usp=sharing

I created issue #35 for heic support.
Please note that path names and.or file names with spaces are currently not supported.

**Comment by hvdwolf** [comment]
Being now on Catalina, I tried this as well.

- JFilechooser: Does not give you access to the smart bar on the left in a normal finder window. Go to your "root hard disk" where you installed Catalina. Go to the `Volumes` folder. Inside that folder you will find your External drive.
- Awt Filedialog: This gives you "native" access to the External disk(s).
