### ISSUE TITLE
Support HEIC (heif) format on MacOS

### ISSUE THREAD

**Issue by hvdwolf** [hvdwolf/jExifToolGUI#35]
Asked in issue #34 as secondary question: support for HEIC format as preview in the tool on MacOS.

To be investigated.

**Comment by hvdwolf** [comment]
MacOS command line tool sips can convert heic to something else. That can be used to create a preview.

sips -s format jpeg -Z 160 test.heic --out test.jpg

**Comment by mrtngrsbch** [comment]
FYI
in Catalina 10.15.5 this command work fine
[sips -s format jpeg -Z 160 test.heic --out test.jpg]

**Comment by ggbalcal** [comment]
Tried 1.4.2. It still didn't show the heic picture.

**Comment by ggbalcal** [comment]
More details:

If I only load one HEIC picture, the thumbnail doesn't render.
If I load one HEIC with other renderable pictures, the HEIC just shows the thumbnail of the picture right before that.

**Comment by hvdwolf** [comment]
That's a pity.

I am now working on the logging to be able to get good logs for
troubleshooting.

Harry

Op di 4 aug. 2020 om 18:42 schreef ggbalcal <notifications@github.com>:

**Comment by mrtngrsbch** [comment]
if the HEIC file, you are NOT the first to read...thumbnails OK
[image: image.png]


But if the HEIC file is the first...
[image: image.png]
Martin GERSBACH
Responsable de Operaciones
mg@museosabiertos.org
www.museosabiertos.org

**Comment by hvdwolf** [comment]
I can't see the images in your mail.

Do you mean:

image-01.heic
image-02.jpg
does not show heic preview.

But
image-01.jpg
image-02.heic
does show the image?

Harry


Op wo 5 aug. 2020 om 07:37 schreef martingggg <notifications@github.com>:

> if the HEIC file, you are NOT the first to read...thumbnails OK
> [image: image.png]
>
>
> But if the HEIC file is the first...
> [image: image.png]
> Martin GERSBACH
> Responsable de Operaciones
> mg@museosabiertos.org
> www.museosabiertos.org
>
>
> El mar., 4 ago. 2020 a las 15:12, HvdWolf (Surfer63) (<

**Comment by mrtngrsbch** [comment]
I tried to send you the attachment... but with the new version you sent me
via mega, it's already obsolete so it doesn't make sense anymore

Martin GERSBACH
Responsable de Operaciones
mg@museosabiertos.org
www.museosabiertos.org

**Comment by hvdwolf** [comment]
heic thumbnails and full screen / full size view are now supported using sips as converting engine. Unfortunately it is not really fast (I am now on MacOS Catalina and could finally test myself and make it work).

To be released in v 1.6.3
