### ISSUE TITLE
XMP Description field problem

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#36]
Hi,

The "Description" field has no line return. Inserted text cannot be read or edited completely

![ScreenShot 2020-07-24 a la(s) 15 28 55](https://user-images.githubusercontent.com/693328/88423866-e35b9180-cdc2-11ea-9d3d-a40134d629d7.jpg)

best,
Martin
jExifToolGUI 1.3.0
OSX 10.15.5
Java 8 Update 261

**Comment by hvdwolf** [comment]
Fixed in 1.4
Edit -> Exif -> Description
Edit -> xmp -> Description
