### ISSUE TITLE
Load directory don't work on OSX

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#40]
Hi,

When I import a directory I have no option to 'accept'. I also can't select the images

![ScreenShot 2020-07-26 a la(s) 01 55 50](https://user-images.githubusercontent.com/693328/88471783-4e9c8500-cee3-11ea-96bb-ff5a6c35d650.jpg)

best,
Martin
OSX 10.15.5
jExifToolGUI 1.4.0
openjdk version "11.0.8" 2020-07-14

**Comment by hvdwolf** [comment]
This is not really a bug (I think). It is strange behavior of Apple. The application remembers the last directoy used, but on Apple  the underlying call "opens" the directory, not select it. Once the directory is open, you have to select the next directory. If you go one directory up, using the blue directory spinner, and then simply click the folder, it will open.
It only works like that on Apple.
I have already been looking at that, but it is something the apple system does.

**Comment by mrtngrsbch** [comment]
hum...
In my case it makes it completely inoperable. I think it's better to see the video in the zip file.
I have no choice but to run the .jar inside the .app

[ScreenShot 2020-07-26 a la(s) 12.48.43.mp4.zip](https://github.com/hvdwolf/jExifToolGUI/files/4977890/ScreenShot.2020-07-26.a.la.s.12.48.43.mp4.zip)

**Comment by hvdwolf** [comment]
Thanks for the video. This makes a lot clear.
Drag & Drop is not supported and  makes parts of the application crash..
drag&drop is on my ToDo list. 

The strange thing is that drag & drop is currently not enabled! Still Apple allows it but that makes the file choosed crash.

**Comment by mrtngrsbch** [comment]
humm... 
I think I have some new revelations...

A. Drag & Drop run OK  **;-)**

B. When I run [/Applications/jExifToolGUI.app/Contents/MacOS/jexiftoolgui] = **black menu**

But when I run [/Applications/jExifToolGUI.app/Contents/MacOS java -jar jExifToolGUI.jar &] = **OK**

[ScreenShot 2020-07-26 a la(s) 15.40.21.mp4.zip](https://github.com/hvdwolf/jExifToolGUI/files/4978198/ScreenShot.2020-07-26.a.la.s.15.40.21.mp4.zip)


best,
Martin

OSX 10.15.5
jExifToolGUI 1.4.0
openjdk version 11.0.8

**Comment by hvdwolf** [comment]
Please try this one from my Google drive (can't upload files >10 MB in issues).
See https://drive.google.com/file/d/1wPyyybkY0kq3S5d83W-C75lNkymL-qfN/view?usp=sharing

See if it still has the black bar and whether it allows for drag&drop (drag&drop not supported, only allowed: I hope)

I started making the application "translatable" and did already some Spanish translations (some easy, some probably completely wrong)

**Comment by mrtngrsbch** [comment]
1. Cuando ejecuto `jExifToolGUI.app` dirctamente:
- black bar NOK
- drag&drop OK
- tif thumbnails NOK

2. Cuando ejecuto `/jExifToolGUI-x86_64 1.4.1/jExifToolGUI.app/Contents/MacOS/jExifToolGUI.jar` 
- bar is OK
- drag&drop OK
- tif thumbnails NOK

3. Cuando ejecuto `/jExifToolGUI-x86_64 1.4.1/jExifToolGUI.app/Contents/MacOS java -jar jExifToolGUI.jar &` 
- bar is OK
- drag&drop OK
- tif thumbnails show OK

best

**Comment by hvdwolf** [comment]
Hmmm,

I have "El Capitan" 10.11.6 (old macbook, can't upgrade)
Application:
 - bar OK
 - drag & drop OK
 - tif(f) OK

from /Applications/jExifToolGUI.app/Contents/MacOS:  ./jexiftoolgui &
 - bar OK
 - drag & drop OK
 - tif(f) OK

from /Applications/jExifToolGUI.app/Contents/MacOS:  java -jar jExiftoolGUI.jar &
 - bar OK
 - drag & drop OK
 - tif(f) OK

It must be something in the "newer" Apple versions. I will google for it.
Secondly: I'm thinking of always(!) using sips on MacOS to convert all tif->jpg,
 and on High sierra or newer use sips to convert heic->jpg for preview viewing.
(I have used sips a lot in the past)

**Comment by mrtngrsbch** [comment]
I'm sorry to tell you that "The Captain" is old when it comes to the changes that OSX has made. But apparently this is important now.

As for sips...I'm also a photographer and I usually use a lot and experiment with new tools, but 'my problems' are always around RAW, CR2, TIF, JPG, EXIF & IPTC and batch rename tools (A Better Finder Rename, Name Changer, Bridge...)
To convert images I use the first tool I have at hand, but when going wrong, I use Exiftool
For me, sips is secondary and I almost don't remember that it exists, but it is the native option of OSX, so it seems right to use it.

As I also work on archives, my problems are currently focused on metadata, such as ISAD(G), EAD, MODS...
As I have told you before, I am planning to extend jExifToolGUI to be able to read and write this metadata.
My first trials were positive, I was able to write and retrieve an arbitrary XML. Here is a test image

Then let it run: #exiftool -support -date-income -institution -CaptionWriter AR-CIFHA-CDV-AS-4-165.tif

many thanks for your kind feedback !

![AR-CIFHA-CDV-AS-4-165](https://user-images.githubusercontent.com/693328/88579160-fc14b300-d01f-11ea-8b0a-36f725232577.jpg)

**Comment by mrtngrsbch** [comment]
FYI
I understand that this is not the topic of this forum, but I take this opportunity to comment that my metadata project must be able to be incorporated into a workflow that includes the audit of a collection.

What I currently do, very clumsily (using EXIF & IPTC)

1- write descriptive metadata in a CSV file
2- reduce original images to test [mogrify -resize 256x256 -path ch *.tif]
3- engraving with Exiftool [exiftool -overwrite_original_in_place -creator=Unknown -title=AR-CIFHA-CDV-AS-1-018 -description="A group of workers pose in front of a house in Cabour.1905 December 10.
Photographic process: album
Size:13 x21 approx.
Tone: Black and white" - "Copyright"="Centro de Investigación Fotográfico Histórico Argentino" - "CopyrightNotice"="Centro de Investigación Fotográfico Histórico Argentino" -CaptionWriter="Carla Fernández, Martin Gersbach" -copyright="Centro de Investigación Fotográfico Histórico Argentino" -url="https://www.cifha.org.ar/legal" AR-CIFHA-CDV-AS-1-018.tif]
4- Export to CVS to see result [exiftool -csv -creator -title -description -copyright  -CaptionWriter AR-CIFHA-CDV-AS-1-001.tif > log.csv]

The idea is to come and go with bulk data

My project consists of not using the spreadsheet at first and allowing editing of metadata directly in jExifToolGUI and then exporting to CSV
A first idea might be this:

![ScreenShot 2020-07-27 a la(s) 16 06 23](https://user-images.githubusercontent.com/693328/88581327-611dd800-d023-11ea-9131-b763e9188fc0.jpg)

best,
Martin

**Comment by hvdwolf** [comment]
I understand what you want. I prefer you simply copy& paste this request into a new issue to keep things separated.
On my ToDo list is also a custom option where you create your own list of tags (and save them), to be able to use them under the "Edit tab"
![modifyable_table](https://user-images.githubusercontent.com/4520361/89068080-d0236580-d370-11ea-8c88-1d2b23d42a3b.png)

It is a bit like the lens configuration option but then more flexible, and looks more like the View tab, but then the value will be editable.
When defining/configuring it,  you only have the first 2 columns Screen name and Tag (you cansearch the tags ffrom the internal database). When right-clicking you get a pop-up with: insert rwo below, insert row above, delete row.
And in the Edit tab under the "Custom" tab you select one of the define custom ones, and then you see Screen name, Tag and Value. In Value you can add your data.
I hope to implement this in 1.6

**Comment by mrtngrsbch** [comment]
1. No problem, it was just an "off topic" note
2. Attention that my idea is not asking you to make it... it's just a draft for my jExifToolGUI [for Archives] idea, but obviously any approach will be welcome ;-)
3. Since I have a Fujifilm x100s camera I can't use the "by camera" filter, so I can't say anything about that experience, yet.
But I do understand how that feature could work.

My idea has other requirements [like exporting an ISAD(G) XML] and if you don't mind me publishing it in a new issue, I'd be happy to detail it there.

best
