### ISSUE TITLE
Translated versions

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#41]
Hi,

Have you thought about giving support to other languages?
If you wish, I offer to collaborate with ES, FR translations

best,
Martin
OSX 10.15.5
jExifToolGUI 1.4.0
openjdk version "11.0.8" 2020-07-14

**Comment by hvdwolf** [comment]
Yes, I have thought about that. It is also mentioned in one of the higher posts in the exiftool forum. But I am dependent on other translators. So if you want to volunteer, that would be great.
It also means that I have to go through the entire app to change all fixed texts to "property based" texts. I will try to put it in v1.5, with an explanation on how to translate.

**Comment by mrtngrsbch** [comment]
Hi
Very good news. I hope this order does not overload your tasks.
I will try to do my best.

Also ... I have an idea of ​​a project to extend jExifToolGUI for edit metadata of archive standard, like ISAD-G and EAD.
I hope I can do it later this year.

Best

**Comment by hvdwolf** [comment]
Implemented.
to be released in 1.5
