### ISSUE TITLE
Reverse buttons in Rename Photos window

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#51]
Users expect to find help on the right...
Please consider reversing the 'Help' and 'Browse' buttons

![image](https://user-images.githubusercontent.com/693328/89741702-d5b43600-da69-11ea-935d-0be70d58f55a.png)

best,
martin

**Comment by hvdwolf** [comment]
You are absolutely right.
Just did that. Will be in 1.5 release.
