### ISSUE TITLE
xmpexport missing ?

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#53]
When I try to export XMP in XMP format I get the error:
`Error: File not found - xmpexport`

![ScreenShot 2020-08-12 a las 07 59 49](https://user-images.githubusercontent.com/693328/90008019-17173200-dc72-11ea-88c4-57c6f87392c0.jpg)

![ScreenShot 2020-08-12 a las 08 00 12](https://user-images.githubusercontent.com/693328/90008034-1d0d1300-dc72-11ea-95d8-e08de997b1f1.jpg)

best,
Martin
OSX 10.15.5
jExifToolGUI 1.4.3
openjdk 11.0.8

**Comment by mrtngrsbch** [comment]
PS: in the "You want to export metadata" window, the "Continue" button should normally be activated

**Comment by hvdwolf** [comment]
Hmm..

That used to be an export option in the older versions, but no longer in the exiftool versions I have on my system.

I will remove it from the options.

I just set the default button to "Continue".

**Comment by mrtngrsbch** [comment]
ok, there is always the option to export a sidecar in ExifTool

**Comment by hvdwolf** [comment]
This makes it clear.
It is a change in exiftool.
The xmpexport is now called xmp sidecar, and has a different syntax.
I will replace the "old" xmpexport with the new "xmp sidecar"
