### ISSUE TITLE
Export CSV to file

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#54]
[minor feature]
Is it possible to export the CSV to a file?

![ScreenShot 2020-08-12 a las 08 36 32](https://user-images.githubusercontent.com/693328/90010963-23ea5480-dc77-11ea-8e38-ac47b27cd872.jpg)

![ScreenShot 2020-08-12 a las 08 36 45](https://user-images.githubusercontent.com/693328/90010977-29479f00-dc77-11ea-9463-d5dbd0c0e10f.jpg)

[Screenshots made in CentOS 7, but same issue in OSX]

{CentOS 7
jExifToolGUI 1.4.3
openjdk 14.0.2}

Best,
Martin
OSX 10.15.5 
jExifToolGUI 1.4.3
openjdk 11.0.8

**Comment by hvdwolf** [comment]
It should export to a csv file, but doesn't do this. That's a bug.
I will check it.

**Comment by hvdwolf** [comment]
csv export repaired. to be relased in 1.5
