### ISSUE TITLE
Application errors at launch

### ISSUE THREAD

**Issue by medmedin2014** [hvdwolf/jExifToolGUI#62]
When launching the app it gives many errors like these:
![Screenshot_20200907_103544](https://user-images.githubusercontent.com/7027319/92373785-c1aa3580-f0f6-11ea-8de0-606c111be3b2.png)
![Screenshot_20200907_103552](https://user-images.githubusercontent.com/7027319/92373789-c2db6280-f0f6-11ea-8541-736cc70158d5.png)
![Screenshot_20200907_103557](https://user-images.githubusercontent.com/7027319/92373792-c373f900-f0f6-11ea-8550-06aff7a0508f.png)
![Screenshot_20200907_103603](https://user-images.githubusercontent.com/7027319/92373796-c40c8f80-f0f6-11ea-9851-4ca229f18665.png)
![Screenshot_20200907_103608](https://user-images.githubusercontent.com/7027319/92373799-c53dbc80-f0f6-11ea-895a-c47ec03445b0.png)
![Screenshot_20200907_103616](https://user-images.githubusercontent.com/7027319/92373821-ce2e8e00-f0f6-11ea-83cd-971d08a307a8.png)
![Screenshot_20200907_103623](https://user-images.githubusercontent.com/7027319/92373823-cf5fbb00-f0f6-11ea-9b9b-a7de2967aa0a.png)
![Screenshot_20200907_103627](https://user-images.githubusercontent.com/7027319/92373826-cff85180-f0f6-11ea-9cab-e51a499d0947.png)
![Screenshot_20200907_103631](https://user-images.githubusercontent.com/7027319/92373830-d090e800-f0f6-11ea-8cde-1d479b927b89.png)
![Screenshot_20200907_103639](https://user-images.githubusercontent.com/7027319/92373835-d1c21500-f0f6-11ea-874a-809f285bf646.png)
![Screenshot_20200907_103647](https://user-images.githubusercontent.com/7027319/92373849-d686c900-f0f6-11ea-9bf9-4b209d59a857.png)
![Screenshot_20200907_103655](https://user-images.githubusercontent.com/7027319/92373851-d7b7f600-f0f6-11ea-8aec-da7c4f28abea.png)
![Screenshot_20200907_103705](https://user-images.githubusercontent.com/7027319/92373854-d8508c80-f0f6-11ea-96b2-871bf84e8838.png)

Launching the app from terminal gives the repeated following error:
`[AWT-EventQueue-0] ERROR o.h.j.controllers.SQLiteJDBC - [SQLITE_ERROR] SQL error or missing database (table CustomMetadatasetLines has no column named rowcount)`

**NB**: Tested both on OpenJDK 11.0.8 and 14.0.2 with the same errors.

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.8.3-2-MANJARO
OS Type: 64-bit
```

**Comment by hvdwolf** [comment]
Hi,

Is this the github version? and from which commit or date?
This is indeed the latest functionality, but should function.
It checks which version database you have and adds the necessary tables and data.
I tsted with databases delivered with 1.0, 1.4 and 1.6.
Can you please attach your database? Please zip it to make it smaller.
`/home/<user>/jexiftoolgui_data/jexiftoolgui.db`

**Comment by medmedin2014** [comment]
Sorry not to mention the app version, it's actually 1.5.2-3.
It's compiled directly from this repository, see https://aur.archlinux.org/packages/jexiftoolgui/
zipped database [jexiftoolgui.db.zip](https://github.com/hvdwolf/jExifToolGUI/files/5182760/jexiftoolgui.db.zip)

**Comment by medmedin2014** [comment]
In this database there is no column named rowcount inside table CustomMetadatasetLines.
![Screenshot_20200907_122349](https://user-images.githubusercontent.com/7027319/92382745-0341dd00-f105-11ea-8bdc-a92c9c8900a5.png)

**Comment by hvdwolf** [comment]
Yes, I know already what is wrong. In the first development version, the table CustomMetadataSetLines did not contain the field rowcount, and now it does and the apps wants to populate it.
Please delete `/home/<user>jexiftoolgui_data/jexiftoolgui.db` (make sure jExifToolGUI is not running).
The database will be recreated on next launch.

That happens when you follow the leading edge developments. Sometimes it is bleeding edge. :wink: 

Just to make sure: please let me know what happens on next launch, after you have removed the database.

**Comment by medmedin2014** [comment]
Yeah you are right, I think the app fails to detect the correct database version with the required new structure, and during launch it performs only a simple test if the database file is present or not without checking if it's outdated.

So when the database structure changes the upgrade process should replace the old database with the new one to fit the new app's requirements.

**Comment by hvdwolf** [comment]
Yes, the database is perfectly upgraded going from one release to another.
The current repo, slightly later than yours, does it correct with with databases of v1.0, 1.4 and 1.5.
But if you compile a version in the middle of development steps like you did, you can run into these kind of issues. It is like that in any development project for any software.
If you want good behavior you need to take a release, not a development version that is in the middel of a cycle.
