### ISSUE TITLE
GUI suggest

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#67]
Hi,

Please consider unifying this tool ;-)

![ScreenShot 2020-09-28 a las 18 26 50](https://user-images.githubusercontent.com/693328/94488265-ae036380-01b8-11eb-9ad0-4cf92cb3a12a.jpg)

If you have space problems, maybe you could use:
Files dropped on the app = loading 

best, martin

**Comment by hvdwolf** [comment]
I understand what you mean but the bottom-right is the "action" status bar. It shows what the program is currently doing together with a infinite progressbar as long as the action is running. Then it disapears.
The bottom left is a static message.
The message  "Files dropped on the app" is maybe confusing. Maybe it is better to change it to "Reading files that were dropped on the app"

**Comment by mrtngrsbch** [comment]
Personally I have no problems...
But maybe it's confusing to see two different reports on the same topic.

Files loaded? dropped? mmm...

I think it could be something like this:
"Files listing" & "Loading files"

**Comment by mrtngrsbch** [comment]
It may be more logical and simple to use this

Files: xxx | Loading files: xxx
