### ISSUE TITLE
Feature Request: Lock fields from being over-written

### ISSUE THREAD

**Issue by Saijin-Naib** [hvdwolf/jExifToolGUI#68]
Ability to "lock" or prevent certain fields from ever being over-written. For instance, using jExifToolGUI to update missing lens information from an adapted lens means that I lose the Software string that Fuji uses to hold camera and firmware combination.

**Suggested Fields for locking:**
EXIF:  
ProcessingSoftware  
Software  

XMP:  
XMPToolkit
Software

Before updating lens:  
![image](https://user-images.githubusercontent.com/19295950/94728100-b4ffb280-032d-11eb-9762-e20933f8e09b.png)

After updating lens:  
![image](https://user-images.githubusercontent.com/19295950/94728180-d5c80800-032d-11eb-86e4-42f71a1adffd.png)

**Comment by hvdwolf** [comment]
I do use the processing software tag. That could be made optional, although I do not like that. What's more: every software does that. If you use the (not supported anymore) ExiftoolGUI, or digikam or photoshop (or my old pyExifToolGUI), you will see that all(!) place their own software stamp and that is also how the software should (!) behave for traceability. For traceability software should not do "anonymous" edits.
The XMPToolkit is hard-coded by Exiftool. There is no way to change that or to stop that. I guess for exactly the same reason: good edit management and traceability (but I did not ask Phil).

**Comment by Saijin-Naib** [comment]
Mmm, perhaps then Software OR ProcessingSoftware could be locked, especially in instances like with Fujifilm cameras where Software stores the body+firmware version combination, which can be very important for tracing changes in behavior between updates. I greatly dislike this field being overwritten, when in effect I'm doing nothing more than fixing missing metadata about the lens.

**Comment by hvdwolf** [comment]
I thought we were talking about Fuji software to deal with the images. If Fuji is really using this fields, it is actually abuse of the fields.
The makernotes are meant for all these items.
I have a very big collection of RAW images from several brands and models to test with, including FUJI RAFs and also from the X-T2.
Only SONY and FUJI abuse this tag. 
NIKON, SIGMA and a few others are also using this tag but only additionally, or when the images were "handled" by their own software. They use the makernotes as they should.
And unfortunately FUJI does not store this info on other places, only in that [exif][software] tag (IFD0:software tag to be more precise)

So actually thanks for reporting this, as I was seriously thinking of changing it, but not only for FUJI as FUJI should learn to do it correctly. Some brands do it really great by specifying which software they used, what the exact lens and firmware of the lens is, what the exact camera body model and firmware is and all in the right places: but not Fuji.

I only consider making the [exif:software] tag optional. I will continue writing the xmp:software tag as not one single camera brand is using that.

**Comment by Saijin-Naib** [comment]
To be clear, these are RAFs straight out of the camera. They have not been touched by ANY software. That tag is being written by the firmware on the camera to store the body+firmware version information.

That is why I'm asking you to consider letting us preserve it, because as you've noted, that is the only place that information is being stored.

**Comment by hvdwolf** [comment]
I know exactly what you mean. I checked against several FUJI RAF images from several FUJI models, incl. the X-T2.
And that's also exactly why I said that FUJI is doing it wrong. (SONY as well but they also store the info in makernotes)
Even in exif there are specific tags for body (make), serial number and firmware version.
FUJI is simply doing it wrong, and as only brand in the 19 brands (with multiple models) I have in my collection.

**Comment by Saijin-Naib** [comment]
I wonder what their reasoning is. I can see this all the way back to my X-A1, X-T1, X-S1, etc. They've been doing this for years, now.

**Comment by emteejay** [comment]
This use is specified in [Exchangeable image file format for digital still cameras: Exif Version 2.32](https://web.archive.org/web/20190624045241if_/http://www.cipa.jp:80/std/documents/e/DC-008-Translation-2019-E.pdf) 

- Software

This tag records the name and version of the software or firmware of the camera or image input device used to generate the image. The detailed format is not specified, but it is recommended that the example shown below be followed. When the field is left blank, it is treated as unknown.
Ex.) "Exif Software Version 1.00a"
Tag = 305 (131h)
Type = ASCII
Count = Any
Default = None

The Application Software Guidelines for the _software_ tag states “Change to name of used software”.

It’s a shame that they do not fill all the appropriate tags.

**Comment by hvdwolf** [comment]
Based on this description FUJI is not doing it wrong, or at least not entirely wrong.
When comparing this with a number of other brands/models, I do see that some only mention a version, which comes back in the makernotes as firmware version, sometimes simplified, sometimes with more subversion numbers.

The strange thing is that you have [exif][software] and [exif][processingsoftware]. The 2nd tag [exif][processingsoftware] can't be found in the document. The 2nd is introduced by ACD systems, but part of the standard.

I do write to -exif:ProcessingSoftware, -exif:Software and -xmp:Software.
I will remove the -exif:Software  from the  "software signing" method/function in the next release.
