### ISSUE TITLE
relation image window and info window

### ISSUE THREAD

**Issue by jos013** [hvdwolf/jExifToolGUI#69]
Normal I would expect a one to one relation between the selected image in the image browser and the shown info in the info window.
When opening a folder the image browser is populated with the files/images. In my case the info window is populated with the info of the first image but that image is **not** accentuated.
When collecting several images in the image browser the info window is showing the info of the last selected image but more images are accentuated. 
In both cases there's no one to one relation anymore.

George

**Comment by hvdwolf** [comment]
To some extend I do agree with you. Maybe this should be made clearer to the user.
On the other hand: The image name is always mentioned in the left pane next to the preview.
The second line on the right side is always the file name (and the 3rd line the folder name). Maybe I am so used to it that this is quite obvious to me, but not to others.

Do you have a suggestion on how to do this?

**Comment by jos013** [comment]
I'm not a programmer. Also a sometime programmer.
I don't know Java, I worked mostly with Clipper and Pascal, lately FreePascal and Lazarus, object oriented.

At the moment the program writes the info you must be able to highlight or accentuate the corresponding file. 
More logical to me would be 1) load the files, 2)accentuate a file and immediately write the info. The code for accentuating and writing the info are connected to each other. Writing the info is a result of the accentuating. But you have that already but not strict.
When more then one file is selected, just empty the info window. There is no relation anymore.

George

**Comment by mrtngrsbch** [comment]
Hi Harry, George,

`When more then one file is selected, just empty the info window. There is no relation anymore.`

I have thought about this but was waiting for a good time to mention it.
I think that when two or more images are selected, the view should change to a reverse table
example:

![image](https://user-images.githubusercontent.com/693328/94814510-d022fe80-03cf-11eb-8096-f2c19e75b4d8.png)

2 or more files selected:
![image](https://user-images.githubusercontent.com/693328/94815432-e7aeb700-03d0-11eb-8726-56a0988429b3.png)

best

**Comment by jos013** [comment]
The image browser can be much smaller. Put the name of the file on top of the image. Now there're 2 columns that I can highlight: the image or the name. 

George

**Comment by hvdwolf** [comment]
I will look into a adding the text above or under the image. My previous program was in python/pySide and there it was simply not possible to put text and an image in one table cell. Moving to java the code did not change much, so I copied and modified the code.

I can currently not judge how high the rows need to be when putting the text above or under the image. This might reduce the widt of the left pane, but at the same time might make a lot of scrolling necessary.
And the buttons on top of the left pane will no longer fit, at least not with the text on it.

**Comment by hvdwolf** [comment]
@mrtngrsbch
I did see your model and most of the export options are simply inside (menu) Metadata -> Export metadata.
Some of the options mentioned for import could be used via Sidecar files, but the import options should be expanded further.

**Comment by mrtngrsbch** [comment]
> I will look into a adding the text above or under the image. My previous program was in python/pySide and there it was simply not possible to put text and an image in one table cell. Moving to java the code did not change much, so I copied and modified the code.
> 
> I can currently not judge how high the rows need to be when putting the text above or under the image. This might reduce the widt of the left pane, but at the same time might make a lot of scrolling necessary.
> And the buttons on top of the left pane will no longer fit, at least not with the text on it.
> 
> **Edit:** I can use buttons with icons on it (folder, files, etc) with a ḧoover/tooltip text if you move the mouse over it.

mmm... Possibly (another idea) it would be appropriate to put a checkbox to "show/hide the file name column

**Comment by mrtngrsbch** [comment]
> @mrtngrsbch
> I did see your model and most of the export options are simply inside (menu) Metadata -> Export metadata.
> Some of the options mentioned for import could be used via Sidecar files, but the import options should be expanded further.

Yes, of course. My layout is old.
Simply the idea was to keep all the export data grouped in the same item.

I think we are solving issues as they arise and then we should rethink the GUI

best

**Comment by hvdwolf** [comment]
Actually I was thinking along parallel, but slightly different  lines.
Dropdown or radiobutton group or Preference option  to select:
- two columns (current layout)
- one column with text above or below
- one column where the filename is a  "tooltip" (currently when you keep your mouse above an image or name  it mentions "Double-clicking the thumbnail or filename will open the image in the default viewer")

But making all options possible requires some complex code (from my current quick analysis)

**Comment by mrtngrsbch** [comment]
mmm... personalmente encuentro un tanto 'extraño' el funcionamiento actual

Considering that we currently have the "view", "edit" and "copy" buttons in one row... why not also have "export" in the same place?
![image](https://user-images.githubusercontent.com/693328/94849277-89e39480-03fb-11eb-9f3b-fa5e160ee686.png)
And in that sense... I think it's exotic that "Exiftool Database" is on that site.

**Comment by mrtngrsbch** [comment]
I also think that the "Load directory" and "Load Images" buttons are not necessary on that site.
and that the "Display image" button could be replaced by a right mouse option.
![image](https://user-images.githubusercontent.com/693328/94849687-3160c700-03fc-11eb-8751-fb3f4347cd46.png)

In this way you could save that space and put a checkbox to show/hide the filename column to gain space for the right panel.

well... they are just ideas ;-)

**Comment by jos013** [comment]
That's all lay-out. More important is the program structure. Still struggling with that relation between the two windows.
When I open just 1 file the metadata is shown of that file all tough the filename is not accentuated. When trying to export that data it says "no file selected". I think solving that problem is more important then the lay out. 

George

**Comment by hvdwolf** [comment]
>I also think that the "Load directory" and "Load Images" buttons are not necessary on that site.
and that the "Display image" button could be replaced by a right mouse option.

I am thinking of "iconified" buttons , as they take less space, with a tooltip when you hoover over them, like displayed (but consistent from one icon set),
![buttons-28](https://user-images.githubusercontent.com/4520361/94904001-ee096580-049a-11eb-9796-17a89cbf3350.png)
or indeed: no buttons at all.
Like mentioned earlier: I want to keep double-click for full size/ full screen view, and right-click for an options popup (where display image could be one of the options)
<br><br>
> And in that sense... I think it's exotic that "Exiftool Database" is on that site.

I agree. All options are acting on images/files. The "Exiftool Database" is not acting on images and should be placed in the menu (or so).
For that same reason it makes more sense to put import/export also in the Tab structure.
<br><br>
> That's all lay-out. More important is the program structure. Still struggling with that relation between the two windows.
> When I open just 1 file the metadata is shown of that file all tough the filename is not accentuated. When trying to export that data it says "no file selected". I think solving that problem is more important then the lay out.
> 

I fully agree with you with regard to the relation in case of multiple files. Being so intensely working on and testing the app, I was blind for it. I already changed that in the program code. 
![multiple_images_select](https://user-images.githubusercontent.com/4520361/94904800-2bbabe00-049c-11eb-910d-6f722d511f2c.png)
"some time" to be released.
However, with regard to the  "no file selected": that is really on purpose to make sure the user does a "well thought" choice/selection. This works exactly the same in many other programs, also non-image like programs, where you have to select "something" to do "something". An option could be to "pre-select" the first image after loading a new set/folder.

**Comment by jos013** [comment]
There's more strange things in the way the program is running.
When looking in the database I'm able to show the tags by group or by brand. When I switch between them the info window doesn't change. I've to select the item that already is selected again. Again there's no one to one relation between the setting window and the info window.

George

**Comment by hvdwolf** [comment]
I have explained that earlier. The database window does NOT act on the images. The text in that database tab even says so.
Changes are happening in the view tab. If you change from exif to xmp (for example), the info changes.
To me this is not:  `There's more strange things in the way the program is running.`

It is like Martin explained, and which I agree upon: the database tab should not be at that place.
The next big release (1.7.0 I think) will be a overhaul of the GUI as I agree on many points with both of you.
The to be released tomorrow (I think) 1.6.3 version will contain some minor "things" and fixes.

**Comment by jos013** [comment]
It's not about the database. It's about a short coming in the programming. 
Lets say the info window should be the result of an event. 

This one is the first. The group button is activated and it matches the selected group.
![jexiftoolgui1](https://user-images.githubusercontent.com/72198589/94988552-64c36300-056e-11eb-92f9-98364f6d174c.jpg)

Then I activate the camera list. It mentions Nikon. The info window is not refreshed.
![jexiftool2](https://user-images.githubusercontent.com/72198589/94988613-c7b4fa00-056e-11eb-9f0c-7ec38e3a593c.jpg)

Although Nikon is selected, I've to select it again.
![jexiftoolgui3](https://user-images.githubusercontent.com/72198589/94988698-76593a80-056f-11eb-9327-106f58cd9733.jpg)

Your info window should be updated also when there is a change of radio button. And the list of the not selected button should not be shown.

Similar to the original post, the info window should be populated only when an image/file is selected. And when more then 1 is selected it has to be emptied.

George

**Comment by hvdwolf** [comment]
Now I understand. When switching radiobuttons inside the database panel, the resulting info should be updated immediately.

This was programmed to work like that. Somehow that does not function anymore. I will look into it.

**Comment by jos013** [comment]
But get rid off the non actual list. It's non info and confusing. Two buttons and one list.

George

**Comment by hvdwolf** [comment]
I did start with the Gui overhaul:
![leftpane](https://user-images.githubusercontent.com/4520361/95750882-131d8580-0c9e-11eb-86ba-1fec00f4bd24.png)

I did not make it smaller as I have other plans with the left pane where I need the current width, but I do agree that a lot of "white space" was waisted on only the filename.

The exiftool database has been removed from the mainscreen tabs:
![image](https://user-images.githubusercontent.com/4520361/95748399-36decc80-0c9a-11eb-8e55-555f7096f045.png)
and now has its own resizable screen
![edbscreen](https://user-images.githubusercontent.com/4520361/95748532-67bf0180-0c9a-11eb-930e-ba06c0f62474.png)

Still quite some steps to make.
