### ISSUE TITLE
Feature Request: File extension mask for "Open Folder"

### ISSUE THREAD

**Issue by Saijin-Naib** [hvdwolf/jExifToolGUI#70]
I'd love to see a File Extension mask functionality for the "Open Folder" functionality, so that only the filetypes I'm interested in working with get loaded/parsed, despite being intermixed in a larger folder.

For instance, I'd love to only view "*.raf", as I will not be making use of the tool for JPG, MP4, or any other filetype.
Having an input field in the Preferences menu might serve for this option.

**Comment by hvdwolf** [comment]
That is not possible. That is not how Exiftool works and that is not how java works when selecting a folder.
For that you need to use "open files".
A personal, configurable file filter created in the "Preferences" (show only *.raf or only *.nef or only *.jpg) might indeed be a nice feature.
But I have many things on my Todo list :)
A current work around is to use your file manager, sort on file type, select and drag the .RAFs (in your case) onto the app.

**Comment by hvdwolf** [comment]
I created the user defined file filter. Was not so difficult.
![userfilefilter](https://user-images.githubusercontent.com/4520361/94946345-47de4f80-04dc-11eb-9a5e-4f3a28346f58.png)
A comma separated list, preferably without spaces, but I will trim them anyway. That is also why I show that here.
If you have defined a filter, it will be used as default filter, but you can change it dynamically.
![filefilters](https://user-images.githubusercontent.com/4520361/94947215-8de7e300-04dd-11eb-9e3a-c581f9f37b84.png)

This will only work using "Load Images" as load folder is a java default method "simply load folder contents". This would require a second step: load everything, loop through all files to remove "not in file filter", start showing thumbs. This is an extremely inefficient way of "selecting" files by folder. It will take too long.

The user defined file filter also works for the Awt filedialog, but as that Awt Filedialog does not support dynamic file filters, you need to remove hte file filter in Preferences to get back to default Awt Filedialog File filter (all exiftool supported formats)

Will be in next release.

**Comment by mrtngrsbch** [comment]
Hi Harry,

I am using jExifToolGUI to record ISAD-G data in PDF files...
It would be great if you could add this file extension to me.

;-)

**Comment by hvdwolf** [comment]
> I am using jExifToolGUI to record ISAD-G data in PDF files...
> It would be great if you could add this file extension to me.

I do not exactly understand what you mean. Do you mean the pdf extension? And added to what? It is part of the "supported_formats".
Or to the "User defined file filter"? You can add any extension there. 
The string behind it is just an example.
I will change it to: `example (comma separated extension list): jpg,cr3,nef,raf,mp4,mie` 
or `example: jpg,cr3,nef,raf,mp4,mie (comma separated)`

**Comment by mrtngrsbch** [comment]
ops
Sorry... I didn't quite understand.
I just meant that I could filter PDF files, but I'm seeing that you've already thought about it.

;-)

**Comment by hvdwolf** [comment]
Please try attached 1.6.3-beta for the file filter
[Windows](https://mega.nz/file/0Rs1XCBK#jsNEjk0bbZmvwYPok_OwYdJxDoyk3O5CQfIIIM1fOmE)

[MacOS](https://mega.nz/file/BY9TzKAB#o7mB4j96ZaNN9FoJf6_aXO2cAo4RjWkAOIcJ47nhmko)

[Universal jar](https://mega.nz/file/wJ91SQ5b#e_DsXs-6AM9ASHAcxGJ3ykV-1AeHxjvA7xvXIS9egE4)

**Comment by mrtngrsbch** [comment]
cool...

![image](https://user-images.githubusercontent.com/693328/94994208-9cc9a680-056c-11eb-9ac0-8e1d50a5c570.png)

**Comment by hvdwolf** [comment]
You first have to create a file filter in Preferences. Something like the mentioned `tif,pdf`. If the field is empty it will just list the current options as in your screen capture (The options in your screen capture have been there since Version 0.99b or so)
Only with a filled in file filter in Preferences you will see the `(user defined file filter)`.
