### ISSUE TITLE
Feature Request: ExifTool Direct Input

### ISSUE THREAD

**Issue by Saijin-Naib** [hvdwolf/jExifToolGUI#71]
A feature from the now-deprecated ExifToolGUI that I've grown quite fond of is the Direct Input field, wherein you can directly paste exiftool parameters that will be written to the selected file(s) without any further ceremony.

A great aspect of this feature is that you can save a number of presets, greatly enhancing some more tedious aspects of metadata updating (manual lens information, for instance).

A final great aspect of this mode is that ONLY the parameters specified will be written, preventing concerns of over-written or updated fields that you don't intend to modify.

**Comment by hvdwolf** [comment]
That is the "Your Commands" tab. 
You can easily put something in there like mentioned in the HELP (behind the button).
You can even save your options as "favorites", making as many commands as you like.
