### ISSUE TITLE
Feature Request: Option to Preserve Date Modified

### ISSUE THREAD

**Issue by Saijin-Naib** [hvdwolf/jExifToolGUI#72]
I'd like to see an option to enable the ability to preserve the Date Modified attribute of the file.

**Comment by hvdwolf** [comment]
No, sorry. That date is exactly there to tell that a file is modified.
The program gives you some options to alter or shift the Modifydate ( for example in case your camera or pc is on the wrong date/time), but I will not make that a configurable option.

**Comment by hvdwolf** [comment]
I downloaded ExifTool GUI and now understands where your question comes from.
I "might" implement this as a "better do not use" option. ExifTool also does this for some tags/options: You can use it, but are advised not to do that.
Maybe in next release.

**Comment by hvdwolf** [comment]
Added the functionality. Preferences -> System
![preservemoddate](https://user-images.githubusercontent.com/4520361/94991874-600aa900-0586-11eb-9c28-64cc1184a4af.png)

Will be available in 1.6.3 (tomorrow?)
