### ISSUE TITLE
'Open folder' NOK in OS X [BUG]

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#74]
'Open folder' feature doesn't work
see video in zip file
[ScreenShot 2020-10-02 a las 10.09.21.mp4.zip](https://github.com/hvdwolf/jExifToolGUI/files/5318171/ScreenShot.2020-10-02.a.las.10.09.21.mp4.zip)

best,
Martin

OS X 10.15.7
ExifToolGUI 1.6.2
Java 11.08.2

**Comment by hvdwolf** [comment]
You are using the AWT filedialog. It is extremely old and I really regret it that I added it on request. One of the big weaknesses is that it actually doesn't support opening folders.
There are multiple bugs registered for MacOS on levels from Sierra, High Sierra, Catalina, etc. ranging from Java7, java8 to Java12. Next to that: the bug happens multiple but is not always 100% reproducible.
Some simply say "use jfilechooser".

I'm a bit without a clue here. I now tried "an old trick". It works on my old El Capitan version (but the current version does as well).
Please try [this version](https://mega.nz/file/oEkSQJAJ#FYWLeauILiAw1L3XpJNXvsrAe3q4tZLT9o1DeFCIzMM)

**Comment by mrtngrsbch** [comment]
Hi,

Estoy usando jfilechooser ;-(

![image](https://user-images.githubusercontent.com/693328/94938769-ac32ec00-04a7-11eb-9ba5-94b420a81d34.png)

**Comment by hvdwolf** [comment]
oh, sorry. I focused on the wrong one.
I will look at the jfilechooser.

**Comment by hvdwolf** [comment]
I made some minor changes specifically to MacOS behavior.
Please try [this version](https://mega.nz/file/BY9TzKAB#o7mB4j96ZaNN9FoJf6_aXO2cAo4RjWkAOIcJ47nhmko). (same as version under #70)

**If that still doesn't work correctly:**
Can you please do the following:
- Open jExifToolGUI and switch off logging (Preferences -> System -> LogLevel -> Off)
- Close jExifToolGUI and open it from a terminal: `open <path_to>/jExifToolGUI.app`

You will see some logging pass by as that is from java itself, the logging class (INFO in ch.qos.logback.core.joran.....) and the process looking at the "drag&drop" (empty watch list...).
Please try the open file dialog and please check if MacOS itself generates errors/warning/logging.

**Comment by mrtngrsbch** [comment]
I have followed your steps and now it works correctly...
But I don't see the errors printed as you indicate

But... now I have discovered a problem (a problem of mine?) of use that is due to that there is a small curiosity of GUI.

- If I click on the folder and press the 'Open' button > it works OK
- But if I 'double click' on the folder, it opens and does NOT show the illuminated files.

I mean... I just tried version 1.6.2 and it works OK, just that curious behavior that has disoriented me

[ScreenShot 2020-10-03 a las 11.56.27.mp4.zip](https://github.com/hvdwolf/jExifToolGUI/files/5321865/ScreenShot.2020-10-03.a.las.11.56.27.mp4.zip)

**Comment by hvdwolf** [comment]
If you double-click on a folder it does indeed open. And only when you have sub-folders below it, you can select these by single-click. If the folder only contains files, you can't select anything.
(And again: if you double-click a sub-folder and that sub-folder only contains files, there is nothing "to OK" either.)

**Comment by mrtngrsbch** [comment]
Yes, excuse me...  I have understood.
But I don't know why I saw an error in this
possibly due to a keyboard overdose ;-/
