### ISSUE TITLE
Export Metadata fail when path contain space

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#83]
Error when exporting metadata (all) if the path contains a space.
This does NOT happen if the path is clean

log:
20:57:27.782 [AWT-EventQueue-0] INFO  o.h.jexiftoolgui.metadata.MetaData - export mie sidecar cmdparams: [/usr/local/bin/exiftool, -tagsfromfile, /Volumes/GoogleDrive/**Mi\ unidad**/_MuseosAbiertos/_Proyectos/
jExifToolGUI/IMG_test/AR-CIFHA-CDV-AS-1-002.tif, -all:all, -icc_profile, /Volumes/GoogleDrive/**Mi\ unidad**/_MuseosAbiertos/_Proyectos/jExifToolGUI/IMG_test/AR-CIFHA-CDV-AS-1-002.mie]

best,
Martin
OSX 10.15.7
jExifToolGUI 1.7.0
openjdk version "11.0.8"

**Comment by hvdwolf** [comment]
In this case you mean the "Metadata" -> "Sidecar Exports".
I can confirm that and I will work on it.
Next to that: I will also move the "Sidecar Exports" to the Export/Import tab

The other export all does not wrok for me. Please let me know if you encounter this as well on on ther locations in the program.

**Comment by mrtngrsbch** [comment]
yes, Of course
...

**Comment by hvdwolf** [comment]
Fixed. 
Will be in new (bugfix) release.

**Comment by hvdwolf** [comment]
released in 1.7.1
