### ISSUE TITLE
Strange behavior in ISAD-G metadata edition

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#87]
I have a strange behavior that I can't solve...

When I see the image metadata (xmp-isadg:ContentstructureScopeContent)= OK
But...
When I open the edit window and copy the image data = NOK

See video & image

[ScreenShot 2020-11-12 a las 14.51.07.mp4.zip](https://github.com/hvdwolf/jExifToolGUI/files/5532325/ScreenShot.2020-11-12.a.las.14.51.07.mp4.zip)

[DP119115.tif.zip](https://github.com/hvdwolf/jExifToolGUI/files/5532331/DP119115.tif.zip)

best,
Martin
OSX 10.15.7
jExifToolGUI 1.7.0
openjdk version "11.0.8"

**Comment by hvdwolf** [comment]
This is the difference of uppercase and lowercase characters.
In the isadg-struct.cfg it is mentioned as `ContentstructureScopecontent`. (lowercase c)
In your custommetadataset is is mentioned as `ContentstructureScope-C-ontent`. (uppercase C)
When viewing data, Exiftool simply reads all tags it can find, no matter whether it is in uppercase or lowercase or spelled wrong. When editing data, you need the exact correct tagname.
Please change your user metadata custom set line to  `ContentstructureScopecontent`.
Then it will work correctly.

**Comment by mrtngrsbch** [comment]
GMO!
I've corrected it and it works OK, thanks Harry !

Now then... I have 
1. custom preset
2. custom config file

![ScreenShot 2020-11-13 a las 10 30 41](https://user-images.githubusercontent.com/693328/99077396-74858c80-259b-11eb-8912-d277686c6b3c.png)

and the file "isadg-struct.cfg" seems correct...
Are they independent? 

best

**Comment by hvdwolf** [comment]
No, they are not independent. Just the contrary.

To start with: exiftool needs to know the exact name of the tag to write to.
To be able to write "non existent" tags, exiftool needs the cfg file to be able to create and write the "non existent" tags and their values.
The tags you use to write, need to be exactly spelled correctly, either in the huge amount of tags exiftool already knows, or by a new cfg file.
That is also why I made "a mistake" in my first movie [user defined combinations simple (01)](https://www.youtube.com/watch?v=FvTN-pMU7yM) to show this. I created a tagname `exif:longitude`  and used that. JTG (or actually exiftool) gave an error on a non-existing tag when writing (in the movie). So I changed it to `exif:gpslongitude` and then it worked correclty. Exiftool needs to have the exact same name.
There is only one difference (I also just found out). Custom tags **are case sensitive**, exiftool's "own" tags are not. You can use exiftool's own tags anyway you like (like eXiF:gPsLoGiTuDe, it doesn't matter).
So, the cfg file is correct. You need to use the tagname from the cfg file, so you need to change inside JTG the tag to `ContentstructureScopecontent`.

Exiftool, and thereby jExifToolGUI, can only write tags it knows from its configuration. Its own internal configuration or an external cfg file.

I do not know why exiftool's "internal" tags can be uppercase or lowercase in any combination. I checked exiftools pm files and I can't find rules that do this "translation".
