### ISSUE TITLE
Edit ALL metadata (feature request ;-)

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#88]
Hi,

Currently we can edit Exif, XMP, Gps, 
![image](https://user-images.githubusercontent.com/693328/99083504-6720d000-25a4-11eb-9667-5cc35db94b43.png)

but... if we want to edit other tags we have no way to do it. For example Photoshop tags
![image](https://user-images.githubusercontent.com/693328/99083821-da2a4680-25a4-11eb-82ac-47c7dfdaf2a8.png)

Could you add a button to edit ALL the metadata?
Or remove other metadata, except...
![image](https://user-images.githubusercontent.com/693328/99084050-2c6b6780-25a5-11eb-9623-053f9926e3fa.png)

best

**Comment by hvdwolf** [comment]
Actually these are 2 feature requests.

To start with the 2nd: 
I can easily add an option to "delete by group". That is easy. (and then do the same for export which is now a "most used set" and by custom metadata sets)

for no 1:
- do you want an editable table of current photoshop tags in the image(s)
- do you want all available photoshop tags in an editable table, even if your image only has 3 photoshop tags?
- or do you want a specific set to be able to edit => Use the custom metadataset combis.

**Comment by mrtngrsbch** [comment]
For 2:
Yes, I think the ability to ONLY delete metadata by groups will be enough.
I currently have images with groups: PNG, Composite, Photoshop, JFIF, MakerNotes, APP14, 

For 1:

- I don't need "Edit" photoshop tags
- I don't need "Edit" photoshop tags
- Exactly how I do it

In practice, I want to be able to "clean up" all those metadata that I don't need.

Now that I see it... why isn't there an edit button for IPTC?

best

**Comment by mrtngrsbch** [comment]
xme...
There is another possibility...

Here I have an image with EXIF data...

![ScreenShot 2020-11-13 a las 13 03 06](https://user-images.githubusercontent.com/693328/99092972-a81ee180-25b0-11eb-9c27-dba2b8848c6c.png)

that I can't remove, because the template doesn't show them to me.
![image](https://user-images.githubusercontent.com/693328/99093070-c389ec80-25b0-11eb-9184-029e07733b2f.png)

best

**Comment by hvdwolf** [comment]
I have mentioned it earlier: I want to give the "User defined Combinations" a more prominent place, maybe with some prepopulated templates. This screen should become the first edit tab.

But I really have not found a good method. This predefined exif screen has 9 fields.
But exif has 432 writable tags (currently), xmp has currently(!) 2194 (!) writable tags and iptc 106. And in total 5790 writable tags (exiftool 12.05)
 I can't simply create a screen using all writable tags. Not one single user would want to use such a screen, or select the 3-7 exif tags he/she really wants to use, plus maybe 2 xmp and 3 iptc tags.
Even if "only" using exif tags (432) or xmp tags (2194) in one screen, not one user wants to use that. Especially if he/she needs a few tags from every category.
So again: the "User defined Combinations" is the way to go, but we needs some userfriendly help options.

**Comment by hvdwolf** [comment]
With regard to "Removing metadata".
That is now functional.
![removecategory2](https://user-images.githubusercontent.com/4520361/99124766-1096ae80-2603-11eb-854d-12bd7c6b6e53.png)

**Comment by mrtngrsbch** [comment]
> I have mentioned it earlier: I want to give the "User defined Combinations" a more prominent place, maybe with some prepopulated templates. This screen should become the first edit tab.
> ...

humm... I understand the problem and I don't see it as viable...
but I think (I think) I have an honorable solution = ExifTool Commands !

I think it's a good problem to be solved with ExifTool directly... because that's why you created it ;-)
por ejemplo: `"exiftool -photoshop:all= MA-DP119115.tif"`

![image](https://user-images.githubusercontent.com/693328/99128329-4464da80-25e9-11eb-9e8e-f4b53fa6db0f.png)

best

**Comment by mrtngrsbch** [comment]
> So again: the "User defined Combinations" is the way to go, but we need some userfriendly help options.

I think (I think) that by making a good manual, with the tags in Google Sheet we can improve that way

**Comment by mrtngrsbch** [comment]
Regarding "ExifTool Commands"... I think for many users this can be very distressing.
I think it would be good to put many more practical commands, como:
`"exiftool -iptc2:all= image.jpg"`
and below a link to: https://exiftool.org/examples.html

![image](https://user-images.githubusercontent.com/693328/99129087-59426d80-25eb-11eb-8c5a-d91d52c83968.png)

Please note that the link is broken !
https://falcon.phy.queensu.ca/SNO/~phil/exiftool/exiftool_pod.html

**Comment by hvdwolf** [comment]
Op vr 13 nov. 2020 om 23:59 schreef martingggg <notifications@github.com>:

> So again: the "User defined Combinations" is the way to go, but we need
> some userfriendly help options.
>
> I think (I think) that by making a good manual, with the tags in Google
> Sheet we can improve that way
>
>
> That's what I suggested when I introduced the "User Defined Combinations"
:)
To somewhere have a place where users can upload all kind of templates in
"spreadsheet"  format, so people can copy & paste from all that examples.

  | Please note that the link is broken !
  | https://falcon.phy.queensu.ca/SNO/~phil/exiftool/exiftool_pod.html

Strange. That is the old link to Phil's old website. I will correct it.

Harry

**Comment by hvdwolf** [comment]
Op za 14 nov. 2020 om 00:07 schreef martingggg <notifications@github.com>:

> Regarding "ExifTool Commands"... I think for many users this can be very
> distressing.
> I think it would be good to put many more practical commands, como:
> "exiftool -iptc2:all= image.jpg"
> and below a link to: https://exiftool.org/examples.html
>
>
> exiftool should not be used before the command and neither the "image.jpg"
as it works on the selected images, but did you really mean "-iptc2:all=" ?
 iptc2 does not exist. Is this a typo or did you mean something completely
different?
I showed the command "-exif:all=" which is actually the same.

The link https://falcon.phy.queensu.ca/SNO/~phil/exiftool/exiftool_pod.html is
only in the spanish translation. It was there in the older versions in both
the help and the string proerties and I replaced it with the good one:
https://www.exiftool.org/exiftool_pod.html in all files.
Somehow that must have got mixed up with the pull requests I'm afraid.
I already changed that in the spanish translation file again now. I also
added a second line.
Ver el <a href="https://www.exiftool.org/exiftool_pod.html"
target="_blank">Documentación del Software ExifTool</a> que ofrece una
amplia información y muchos ejemplos.<br>
Ver también el <a href="https://exiftool.org/examples.html"
target="_blank">Exiftool Command-Line examples</a> que también ofrece
muchos ejemplos.
I will also add the link to the examples page. Note though that that
examples page is very old.

Harry

**Comment by hvdwolf** [comment]
Released the "remove all metadata per category" in 1.7.1
