### ISSUE TITLE
Tag ordered list

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#90]
Hi,

Sería posible ordenar alfabéticamente la lista de tags?Would it be possible to sort the list of tags alphabetically?

![ScreenShot 2020-11-19 a las 13 48 03](https://user-images.githubusercontent.com/693328/99696882-f2e7a000-2a6d-11eb-976d-a67d3d967d03.png)

best

**Comment by hvdwolf** [comment]
Yes, that's possible. 
exiftool reads tags as they are stored in the image.
I will make it a Preference Setting.

If I display them in alphabetical order, It will be slighlty slower, but less than 50 millisecs slower I assume (Same as for the "compare images" functionality)

**Comment by mrtngrsbch** [comment]
I think it will be profitable.
I have images with @50 XMP lines and it is hard to find a tag

best

**Comment by hvdwolf** [comment]
No need to convince me :smiley:
I already implemented it: Preferences -> System -> Sort Categories/Tags in View tab alphabetically
Will be in next release.
