### ISSUE TITLE
Focal length in 35 mm shown as null

### ISSUE THREAD

**Issue by emteejay** [hvdwolf/jExifToolGUI#98]
In the "File data" field:
Focal length in 35 mm: **null** mm
it is correct in the composite focal length tag.

![Screenshot 2020-12-06 16-05-07](https://user-images.githubusercontent.com/1093171/101285660-526bdc80-37de-11eb-8856-83802cdacef7.png)

**Comment by hvdwolf** [comment]
This is obviously a bug, but I do not understand yet why.

Can you fill in the "Exiftool Commands" pane `-focallengthin35mmformat`, select the image  and tap the "Go" button?
Or otherwise execute from the terminal `exiftool -focallengthin35mmformat IMG_0065.JPG`

**Comment by emteejay** [comment]
martin@Ant:06$ exiftool -focallengthin35mmformat IMG_0065.JPG
martin@Ant:06$ exiftool -focal\* IMG_0065.JPG
Focal Length                    : 135.0 mm
Focal Units                     : 1/mm
Focal Plane X Resolution        : 6825.938567
Focal Plane Y Resolution        : 6825.938567
Focal Plane Resolution Unit     : inches
Focal Length                    : 135.0 mm (35 mm equivalent: 217.7 mm)
martin@Ant:06$

**Comment by emteejay** [comment]
martin@Ant:06$ exiftool -ver
11.16

**Comment by hvdwolf** [comment]
Thanks.
It is your camera: it doesn't deliver the `focallengthin35mmformat`. Both my cameras (and previous cameras) deliver both the `focallengthin35mmformat` as well as the  `ScaleFactor35efl` (in your screenshot `Scale Factor to 35 mm Equivalent` being 1.6). I never thought of that as all of my 6 digital cameras delivered both (just checked also my old photos).
Exiftool is so smart to calculate it itself if it can't find the `focallengthin35mmformat`, which means that I actually should try to read both tags and use the ` ScaleFactor35efl` with the `focallength` to calculate the correct value if the `focallengthin35mmformat` is not in the image.

I see in my raw collection (mostly downloaded, some of my own cameras) that Canon doesn't deliver the `focallengthin35mmformat` and some of the FUJI RAWs neither.

**Comment by hvdwolf** [comment]
Implemented. 
Also: I just retrieved the metadata values whether they were there or not. Some users work on images that are not photographic images at all. They do not have metadata like ISO, fnumber, focallength, etc. These now show "Not available".

To be released in 1.8.1
