### ISSUE TITLE
3 issues > GPS edition

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#99]
Open "Find Location" & paste "copy to GPS tab"
![image](https://user-images.githubusercontent.com/693328/101285462-0ad85700-37c4-11eb-999d-ec7a38e86f36.png)

It copies the coordinates in both formats
![image](https://user-images.githubusercontent.com/693328/101285404-d06eba00-37c3-11eb-96c1-faa51d36f4b2.png)
![image](https://user-images.githubusercontent.com/693328/101285413-d95f8b80-37c3-11eb-914e-12cdd0a1bbe9.png)

Nice, it works perfectly!

Pero...
1. "Reset fields" does not delete the Deg-mig-sec data (I can only delete it by restarting the application)

2. When "Copy from selected images" the coordinates do not show the negative degrees

![image](https://user-images.githubusercontent.com/693328/101285574-b681a700-37c4-11eb-8f70-6b941ce86d58.png)
![image](https://user-images.githubusercontent.com/693328/101285605-ea5ccc80-37c4-11eb-9b0a-9504728d11a4.png)

3. "Save to selected image" does not work when I am on the tab"Deg-min-sec format"
![image](https://user-images.githubusercontent.com/693328/101285898-82a78100-37c6-11eb-98a3-44ad8b08ee5a.png)

best,
Martin
MacOS 10.15.7
jExifToolGUI 1.8.0
openjdk version "11.0.8"

**Comment by hvdwolf** [comment]
1. "Reset fields" does not delete the Deg-mig-sec data (I can only delete it by restarting the application)
  Completey forgot to do that.

2. When "Copy from selected images" the coordinates do not show the negative degrees
  I will check.

3. "Save to selected image" does not work when I am on the tab "Deg-min-sec format"
  This was thoroughly tested. I will check.

**Comment by hvdwolf** [comment]
All 3 fixed. Will be in 1.8.1 which will be soon released.
